MCF ITB 2025 - Code Documentation

In [3]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import TimeSeriesSplit

In [4]:
data_claim = pd.read_csv("data/Data_Klaim.csv")

In [5]:
data_claim

,Claim ID,Nomor Polis,Reimburse/Cashless,Inpatient/Outpatient,ICD Diagnosis,ICD Description,Status Klaim,Tanggal Pembayaran Klaim,Tanggal Pasien Masuk RS,Tanggal Pasien Keluar RS,Nominal Klaim Yang Disetujui,Nominal Biaya RS Yang Terjadi,Lokasi RS
0,C-0001-M,POL-0176,R,OP,C50,MALIGNANT NEOPLASM OF BREAST,PAID,2024-07-08,2024-05-27,2024-05-27,2.809365e+07,6.143948e+06,Singapore
1,C-0002-M,POL-3288,R,OP,C34,MALIGNANT NEOPLASM OF BRONCHUS AND LUNG,PAID,2024-08-06,2024-07-15,2024-07-15,8.098728e+07,8.230952e+07,Malaysia
2,C-0003-M,POL-1786,R,OP,C18.9,"MALIGNANT NEOPLASM, COLON, UNSPECIFIED",PAID,2024-10-17,2024-05-16,2024-05-16,1.830471e+08,1.928599e+08,Singapore
3,C-0004-M,POL-1786,R,OP,C34,MALIGNANT NEOPLASM OF BRONCHUS AND LUNG,PAID,2024-09-03,2024-07-18,2024-07-18,1.914244e+08,1.914244e+08,Singapore
4,C-0005-M,POL-2778,R,OP,C50,MALIGNANT NEOPLASM OF BREAST,PAID,NaN,2024-06-06,2024-06-06,1.389364e+08,1.389364e+08,Singapore
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,C-5777-M,POL-3288,C,IP,C34,Malignant neoplasm of bronchus and lung,PAID,2025-07-02,2025-03-11,2025-03-11,1.513929e+07,1.531253e+07,Malaysia
4623,C-5778-M,POL-3288,C,IP,C34,Malignant neoplasm of bronchus and lung,PAID,2025-07-08,2025-04-18,2025-04-18,6.336514e+07,6.620405e+07,Malaysia
4624,C-5779-M,POL-3288,C,IP,C34.1,"Malignant neoplasm of upper lobe, bronchus or ...",PAID,NaN,2025-05-21,2025-05-21,1.632886e+07,1.651873e+07,Malaysia
4625,C-5780-M,POL-3288,C,IP,C34.9,"Malignant neoplasm of bronchus or lung, unspec...",PAID,NaN,2025-06-30,2025-06-30,6.540838e+07,6.662646e+07,Malaysia
4626,C-5781-M,POL-3288,C,IP,C34.1,"Malignant neoplasm of upper lobe, bronchus or ...",PAID,2025-03-12,2025-01-07,2025-01-07,1.538734e+07,1.556434e+07,Malaysia

In [6]:
for feature in data_claim.columns:
    print("{} has {} unique value". format(feature,data_claim[feature].unique()))
    print('-'*20)

Claim ID has ['C-0001-M' 'C-0002-M' 'C-0003-M' ... 'C-5779-M' 'C-5780-M' 'C-5781-M'] unique value
--------------------
Nomor Polis has ['POL-0176' 'POL-3288' 'POL-1786' ... 'POL-2878' 'POL-3156' 'POL-0264'] unique value
--------------------
Reimburse/Cashless has ['R' 'C'] unique value
--------------------
Inpatient/Outpatient has ['OP' 'ODC' 'IP' nan 'ODS'] unique value
--------------------
ICD Diagnosis has ['C50' 'C34' 'C18.9' 'C90.0' 'C82.9' 'L02.2' 'A09' 'A90' 'S00.0' 'H26.9'
 'K29.7' 'K57' 'I49.5' 'R50.9' 'J18' 'M17' 'I62.0' 'I67.1' 'C56' 'H26'
 'M54.5' 'G57.1' 'S82.2' 'I63.9' 'H25.9' 'I95.9' 'L03.1' 'L03.9' 'L12.0'
 'J96' 'H35.9' 'L03' 'I67' 'J70.4' 'J84.9' 'K29' 'R10' 'J20' 'S52' 'S52.0'
 'N18.0' 'N23' 'N18.6' 'I87' 'G62.9' 'D07.5' 'C61' 'N70.1' 'N70' 'S09'
 'I25.1' 'K63.5' nan 'R11' 'G40.2' 'R56.9' 'N20.1' 'N20' 'D25.9' 'E86.0'
 'R57' 'N39.0' 'R07.4' 'K63.8' 'M75.1' 'A49' 'I84' 'K30' 'H40.2' 'C85.9'
 'H35' 'H35.0' 'K63.9' 'K21' 'I63.6' 'I63' 'M48.0' 'K80.0' 'H25.1' 'M67.4'
 'H25' 'T14' 'H26.4' 'J45' 'E88.0' 'D64.9' 'M43.0' 'L02' 'I25' 'K52.9'
 'S83.2' 'C34.3' 'D02.2' 'M65.3' 'M13.9' 'M89.4' 'M54.1' 'M54.3' 'M87.0'
 'M54.4' 'M87.1' 'A91' 'M46.0' 'D48.6' 'K29.3' 'R56.1' 'F05' 'R06' 'K51.9'
 'K52.0' 'I21.1' 'N18' 'B34.2' 'D21.0' 'H81.4' 'C71.9' 'J06' 'R50' 'J34.8'
 'R04.0' 'I25.0' 'S42' 'S42.0' 'H35.4' 'C79.3' 'G44' 'N84.0' 'N20.0'
 'H43.1' 'D20' 'M20.0' 'I50.9' 'K51.8' 'K52.1' 'R00.2' 'M51' 'I48' 'J38.0'
 'I82.4' 'A41' 'A41.9' 'C34.1' 'J18.9' 'K57.9' 'N15.1' 'J45.9' 'N81.6'
 'M25.5' 'M25.51' 'J35.0' 'J03' 'D23' 'S46.0' 'I21.4' 'I42.2' 'C49.2'
 'D21.2' 'M16.9' 'M16' 'K92.1' 'R10.4' 'S72' 'M62.6' 'N13.2' 'N13.3' 'R31'
 'L08.9' 'E78.5' 'E04.2' 'K57.3' 'N87.9' 'S93.2' 'K01.1' 'H33.2' 'H60.0'
 'M54.2' 'N93.8' 'H82' 'I67.6' 'R06.0' 'H81.1' 'H35.3' 'H40.1' 'J09'
 'E78.4' 'E10.5' 'M25.6' 'N84' 'M17.1' 'Z00.0' 'K80' 'B34' 'D55.0' 'S83'
 'S83.5' 'H59' 'F03' 'N28.9' 'H44.9' 'D37.4' 'M51.2' 'M51.0' 'K80.1' 'C22'
 'J02' 'I63.0' 'I20.9' 'C50.9' 'C44' 'C18.7' 'C18' 'C19' 'K21.0' 'N35.9'
 'N40' 'L72.0' 'S61' 'T81.3' 'I10' 'J37' 'I15' 'S22' 'H61' 'R32' 'N99'
 'C67.5' 'N32.0' 'Q64.3' 'M51.1' 'R42' 'K58' 'M17.0' 'C08' 'M53.0' 'D14.0'
 'M54.8' 'E11' 'H11.0' 'S32.2' 'K40' 'K62.1' 'S93.4' 'S82.0' 'R55' 'K25.9'
 'G56.0' 'D45' 'K21.9' 'G44.1' 'A09.0' 'L23.9' 'K20' 'M50.8' 'M43.1'
 'M48.00' 'K20.9' 'L02.4' 'C34.9' 'E13.6' 'K36' 'K35' 'J00' 'D25' 'N82'
 'K50' 'K51' 'I47' 'K76' 'K31' 'E87.2' 'M16.1' 'K29.6' 'K25' 'E87.1'
 'A15.0' 'M48.82' 'S66.3' 'S33.0' 'C20' 'D70.9' 'I20' 'R51' 'N86' 'C91'
 'H81.3' 'L82' 'N95.0' 'N85.1' 'D24' 'G44.0' 'I67.9' 'I73.9' 'M41.2'
 'K51.4' 'I87.2' 'D59.1' 'C25' 'G51.3' 'H40.0' 'C80' 'H25.8' 'E13.0'
 'M50.0' 'J06.9' 'K29.1' 'I85.9' 'D55.1' 'J90' 'K82' 'M17.9' 'I82.9'
 'S82.1' 'S69' 'M65.8' 'S66' 'K76.0' 'M70.7' 'N63' 'K62.5' 'L84' 'R47.0'
 'E87.6' 'K31.9' 'M50' 'K29.5' 'C49.9' 'J30.4' 'N30' 'I50.0' 'K81' 'M75.3'
 'N32.9' 'H04.0' 'H58' 'H25.0' 'K22.9' 'I47.1' 'M19.9' 'I89.0' 'L30'
 'M65.4' 'S22.00' 'E11.9' 'R20.2' 'T18.4' 'N10' 'E78' 'N21' 'E04.8'
 'N18.9' 'A01' 'A01.0' 'K60.3' 'D12.6' 'K86.2' 'C65' 'S00.9' 'C22.0'
 'N82.3' 'L40.5' 'S00' 'H00.1' 'C78.0' 'M89.3' 'K31.8' 'K00.1' 'H52.2'
 'S62.3' 'S52.5' 'E10' 'D17.0' 'K44.0' 'S82' 'J94.8' 'E04.1' 'E06' 'N28.1'
 'S01.1' 'N39' 'R10.2' 'M79.4' 'H33.3' 'I62' 'G40.3' 'K29.0' 'D14.3'
 'J98.4' 'C79' 'C25.9' 'K82.8' 'H40' 'C73' 'B37.8' 'K62.6' 'K51.1' 'I21'
 'T80.2' 'J34' 'D69.6' 'M50.1' 'E05' 'M53' 'K40.9' 'C64' 'Z48' 'D33' 'J32'
 'M96.8' 'E88.9' 'I20.0' 'I11.0' 'N18.5' 'D36' 'D21' 'C55' 'S06.0' 'K81.0'
 'M23.3' 'I84.5' 'D64' 'J39.9' 'M75.0' 'C50.8' 'K83.1' 'B34.9' 'D21.9'
 'C16' 'M75' 'M75.9' 'N92' 'S32.0' 'A49.9' 'H33' 'H33.5' 'H35.6' 'M75.8'
 'J18.0' 'M72.2' 'G31.8' 'R07' 'G51' 'L24' 'J01.9' 'J34.3' 'M46' 'R73.9'
 'E16.2' 'R65.2' 'H00' 'K35.9' 'M50.2' 'M75.5' 'S43.3' 'G95.2' 'M47'
 'S43.7' 'S33.7' 'S73.1' 'K52' 'I65.2' 'E87.8' 'I69.3' 'M76.6' 'M77.1'
 'A27.9' 'S42.1' 'S52.1' 'R40.1' 'E11.0' 'R40.0' 'D17.1' 'S90' 'S93'
 'S83.3' 'K26.9' 'D33.3' 'I24.9' 'E83' 'D34' 'A88.1' 'Z94.0' 'I84.1'
 'D29.1' 'J15' 'D18' 'K51.2' 'C49.1' 'M65' 'J22' 'E27.1' 'C76.2' 'R22.1'
 'H33.0' 'B07' 'C44.3' 'K42' 'C79.8' 'D32.9' 'C17.2' 'S42.2' 'E13' 'C37'
 'J40' 'N80' 'C54.1' 'M99.0' 'M47.8' 'C22.9' 'C78.7' 'C40' 'K76.9' 'L72.3'
 'K62' 'K76.8' 'K85' 'M84.4' 'I44.2' 'M81' 'R30.0' 'N83.2' 'K63' 'G93.9'
 'G93.8' 'N21.0' 'K44.9' 'I11' 'H26.8' 'C83' 'K80.5' 'E87' 'E14.9' 'H18'
 'H01.0' 'G93.4' 'G82.5' 'H34.2' 'G25.3' 'R10.0' 'S80.0' 'G45.9' 'G46.8'
 'G54.2' 'D22' 'D11.0' 'D10' 'D17' 'D17.9' 'D25.1' 'D69.3' 'D72.8' 'J03.9'
 'J04.0' 'I96' 'J30.0' 'J10.1' 'I50' 'I51.9' 'I50.2' 'S62' 'I70.9' 'I64'
 'K27.9' 'K25.7' 'K31.7' 'J44.1' 'J98.0' 'J81' 'J96.9' 'J32.0' 'H40.9'
 'I48.9' 'M54.12' 'I11.9' 'I21.0' 'H93.1' 'A18' 'J01' 'B02' 'S52.90'
 'A17.8' 'C54' 'C53' 'C82' 'C18.4' 'C49' 'M86.9' 'L30.9' 'R07.9' 'G40.9'
 'N11.0' 'M14.6' 'J20.9' 'N42.0' 'K64.8' 'S72.0' 'S82.01' 'J01.0' 'L04'
 'M24.17' 'R97.2' 'H27' 'R07.1' 'N30.9' 'S82.6' 'S82.4' 'N13' 'N13.1'
 'N13.0' 'N85.0' 'N84.1' 'G89.0' 'R29.0' 'R04.2' 'R13.1' 'R17' 'N40.1'
 'S09.9' 'K92.0' 'K92.2' 'M48.06' 'M48.02' 'L02.9' 'L03.0' 'L02.3' 'K56.3'
 'K44' 'K35.8' 'K42.9' 'K63.1' 'K64.3' 'K64' 'M53.82' 'R53.1' 'M25.4'
 'M45' 'M46.1' 'M46.9' 'M12.8' 'L97' 'L89' 'K56.7' 'M65.0' 'R47.1' 'R63'
 'S92.0' 'S92' 'T30.0' 'S03.9' 'S02.2' 'S92.3' 'T84.7' 'R56' 'J42' 'N30.3'
 'R60' 'M08.2' 'J15.9' 'I71.4' 'K40.2' 'M53.00' 'K83.0' 'R05' 'K80.4'
 'Z96.1' 'N42.8' 'H25.2' 'R39' 'I95.1' 'E11.6' 'N30.0' 'L02.8' 'K83.9'
 'A01.4' 'I63.3' 'I63.8' 'E78.0' 'N17' 'I25.5' 'D22.6' 'D35.2' 'K64.9'
 'H04.5' 'M21.9' 'S43.1' 'H90.4' 'G50' 'G50.0' 'S01.5' 'K74' 'K80.2'
 'D61.8' 'T84.9' 'I24.0' 'K27.2' 'G57.8' 'M46.36' 'D61.9' 'E14' 'D61'
 'D50' 'R19.5' 'C44.9' 'N93.9' 'M19.0' 'D09.3' 'M13.8' 'K31.4' 'I85.0'
 'M86' 'M54.16' 'N41.0' 'S93.0' 'K62.8' 'W55.99' 'I63.5' 'M79' 'I84.0'
 'N80.0' 'M43.16' 'S63.6' 'M65.14' 'M76.0' 'S69.9' 'M24.39' 'N21.1'
 'S27.3' 'C66' 'G91.2' 'C78.8' 'C41.9' 'C41' 'R10.9' 'J12.8' 'H04' 'C64.2'
 'A06' 'N61' 'N17.9' 'K29.9' 'N35' 'G43' 'N47' 'J01.4' 'J04' 'N36' 'M47.9'
 'K11.2' 'A05.9' 'S86.8' 'c50' 'C50.6' 'B37' 'C90' 'R56.0'] unique value
--------------------
ICD Description has ['MALIGNANT NEOPLASM OF BREAST' 'MALIGNANT NEOPLASM OF BRONCHUS AND LUNG'
 'MALIGNANT NEOPLASM, COLON, UNSPECIFIED' 'Multiple myeloma'
 "Follicular non-Hodgkin's lymphoma, unspecified"
 'Cutaneous abscess, furuncle and carbuncle of trunk'
 'OTHER GASTROENTERITIS AND COLITIS OF INFECTIOUS AND UNSPECIFIED ORIGIN'
 'DENGUE FEVER [CLASSICAL DENGUE]' 'SUPERFICIAL INJURY OF SCALP'
 'Cataract, unspecified' 'GASTRITIS' 'Diverticular disease of intestine'
 'SICK SINUS SYNDROME' 'FEVER, UNSPECIFIED'
 'PNEUMONIA, ORGANISM UNSPECIFIED' 'GONARTHROSIS [ARTHROSIS OF KNEE]'
 'SUBDURAL HAEMORRHAGE (ACUTE)(NONTRAUMATIC)'
 'CEREBRAL ANEURYSM, NONRUPTURED' 'Malignant neoplasm of ovari'
 'Malignant neoplasm of ovary' 'OTHER CATARACT'
 'Low back pain (Nyeri punggung)' 'Meralgia paraesthetica'
 'FRACTURE OF SHAFT OF TIBIA' 'CEREBRAL INFARCTION, UNSPECIFIED'
 'Senile cataract, unspecified' 'HYPOTENSION, UNSPECIFIED'
 'CELLULITIS OF OTHER PARTS OF LIMB' 'CELLULITIS, UNSPECIFIED'
 'BULLOUS PEMPHIGOID' 'RESPIRATORY FAILURE, NOT ELSEWHERE CLASSIFIED'
 'RETINAL DISORDER, UNSPECIFIED' 'CELLULITIS'
 'OTHER CEREBROVASCULAR DISEASES'
 'DRUG-INDUCED INTERSTITIAL LUNG DISORDERS, UNSPECIFIED'
 'Interstitial pulmonary disease, unspecified' 'GASTRITIS AND DUODENITIS'
 'ABDOMINAL AND PELVIC PAIN' 'ACUTE BRONCHITIS' 'FRACTURE OF FOREARM'
 'FRACTURE OF UPPER END OF ULNA' 'END-STAGE RENAL DISEASE'
 'Diarrhoea and Gastroenteritis of presumed infectious origin(GED)'
 'UNSPECIFIED RENAL COLIC' 'END STAGE RENAL DISEASE'
 'OTHER DISORDERS OF VEINS' 'POLYNEUROPATHY, UNSPECIFIED'
 'Carcinoma in situ of prostate' 'MALIGNANT NEOPLASM OF PROSTAT'
 'Chronis salpingitis and oophoritis' 'Salpingitis and oophoritis'
 'OTHER AND UNSPECIFIED INJURIES OF HEAD' 'ATHEROSCLEROTIC HEART DISEASE'
 'POLYP OF COLON' 'Other Cataract' nan
 'Nausea and Vomiting (mual dan muntah)'
 'LOCALIZATION-RELATED (FOCAL)(PARTIAL) SYMPTOMATIC EPILEPSY AND EPILEPTIC SYNDROMES WITH COMPLEX PARTIAL SEIZURES'
 'UNSPECIFIED CONVULSIONS' 'CALCULUS OF URETER' 'Urolithiasis'
 'LEIOMYOMA OF UTERUS, UNSPECIFIED' 'DEHYDRATION'
 'Shock - not elsewhere classified'
 'URINARY TRACT INFECTION- SITE NOT SPECIFIED' 'Chest Pain'
 'Other specified diseases of intestine' 'Rotator cuff syndrome'
 'BACTERIAL INFECTION OF UNSPECIFIED SITE' 'Haemorrhoids (ambein)'
 'GASTRITIS, UNSPECIFIED' 'FUNCTIONAL DYSPEPSIA'
 'Primary angle-closure glaucoma' 'NON-HODGKIN LYMPHOMA, UNSPECIFIED'
 'Other Retinal disorders'
 'Background retinopathy and retinal vascular changes'
 'DISEASE OF INTESTINE- UNSPECIFIED' 'Gastro-oesophageal reflux disease'
 'OTHER RETINAL DISORDERS'
 'Cerebral infarction due to cerebral venous thrombosis, nonpyogenic'
 'Cerebral Infarction'
 'CEREBRAL INFARCTION DUE TO CEREBRAL VENOUS THROMBOSIS, NONPYOGENIC'
 'CORONARY ATRIAL DISEASES (CAD)' 'SPINAL STENOSIS'
 'CALCULUS OF GALLBLADDER WITH ACUTE CHOLECYSTITIS'
 'Senile nuclear cataract' 'Ganglion' 'Senile Catharact'
 'INJURY OF UNSPECIFIED BODY REGION' 'AFTER-CATARACT' 'Asthma'
 'DISORDERS OF PLASMA-PROTEIN METABOLISM, NOT ELSEWHERE CLASSIFIED'
 'ANAEMIA, UNSPECIFIED' 'CHEST PAIN, UNSPECIFIED' 'Spondylosis'
 'CUTANEOUS ABSCESS, FURUNCLE AND CARBUNCLE'
 'Chronic Ischaemic Heart Disease'
 'NONINFECTIVE GASTROENTERITIS AND COLITIS, UNSPECIFIED'
 'Tear of meniscus, current'
 'MALIGNANT NEOPLASM, LOWER LOBE, BRONCHUS OR LUNG' 'Bronchus and lung'
 'Trigger finger (Nodular tendinous disease)' 'ARTHRITIS, UNSPECIFIED'
 'Other hypertrophic osteoarthropathy' 'Radiculopathy'
 'Lumbago with sciatica' 'Gonarthrosis [arthrosis of knee]'
 'Idiopathic aseptic necrosis of bone' 'Osteonecrosis due to drugs'
 'OSTEONECROSIS DUE TO DRUGS' 'IDIOPATHIC ASEPTIC NECROSIS OF BONE'
 'Dengue Haemorrhagic Fever (demam berdarah dengue)' 'Spinal enthesophaty'
 'LOW BACK PAIN' 'NEOPLASM OF UNCERTAIN OR UNKNOWN BEHAVIOUR, BREAST'
 'Chronic superficial gastritis' 'POST TRAUMATIC SEIZURES'
 'DELIRIUM, NOT INDUCED BY ALCOHOL AND OTHER PSYCHOACTIVE SUBSTANCES'
 'ABNORMALITIES OF BREATHING' 'Ulcerative colitis'
 'Gastroenteritis and colitis due to radiation'
 'ACUTE TRANSMURAL MYOCARDIAL INFARCTION OF INFERIOR WALL'
 'Chronic Renal Failure  (CRF)' 'CORONAVIRUS INFECTION, UNSPECIFIED SITE'
 'Connective and other soft tissue of head, face and neck'
 'VERTIGO OF CENTRAL ORIGIN' 'MALIGNANT NEOPLASM, BRAIN, UNSPECIFIED'
 'Acute upper respiratory infections of multiple and unspecified sites/URTI/ ISPA'
 'Fever  of Unknown origin'
 'BENIGN NEOPLASM, CONNECTIVE AND OTHER SOFT TISSUE OF HEAD, FACE AND NECK'
 'Brain, unspecified'
 'Other specified disorders of nose and nasal sinuses'
 'Epistaxis (mimisan)'
 'Atherosclerotic cardiovascular disease, so described' 'EPISTAXIS'
 'Fracture of shoulder and upper arm' 'FRACTURE OF CLAVICLE'
 'Peripheral retinal degeneration'
 'SECONDARY MALIGNANT NEOPLASM OF BRAIN AND CEREBRAL MENINGES'
 'OTHER HEADACHE SYNDROMES' 'POLYP OF CORPUS UTERI'
 'DENGUE HAEMORRHAGIC FEVER' 'CALCULUS OF KIDNEY' 'vitreous haemorrhage'
 'BENIGN NEOPLASM OF SOFT TISSUE OF RETROPERITONEUM AND PERITONEUM'
 'DEFORMITY OF FINGER(S)' 'HEART FAILURE, UNSPECIFIED'
 'Other ulcerative colitis' 'TOXIC GASTROENTERITIS AND COLITIS'
 'PALPITATIONS' 'OTHER INTERVERTEBRAL DISC DISORDERS'
 'Atrial fibrillation and flutter' 'Paralysis of vocal cord and larynx'
 'ACUTE EMBOLISM AND THROMBOSIS OF DEEP VEINS OF LOWER EXTREMITY'
 'OTHER SEPSIS' 'SEPSIS, UNSPECIFIED' 'RADICULOPATHY'
 'MALIGNANT NEOPLASM, UPPER LOBE, BRONCHUS OR LUNG'
 'PNEUMONIA, UNSPECIFIED'
 'DIVERTICULAR DISEASE OF INTESTINE, PART UNSPECIFIED, WITHOUT PERFORATION OR ABSCESS'
 'RENAL AND PERINEPHRIC ABSCESS' 'ASTHMA, UNSPECIFIED'
 'ACUTE UPPER RESPIRATORY INFECTIONS OF MULTIPLE AND UNSPECIFIED SITES'
 'Rectocele' 'PAIN IN JOINT' 'PAIN IN JOINT, SHOULDER REGION'
 'Chronic tonsilitis' 'ACUTE TONSILLITIS' 'OTHER BENIGN NEOPLASMS OF SKIN'
 'ROTATOR CUFF SYNDROME' 'Injury of tendon of the rotator cuff of sholder'
 'ACUTE SUBENDOCARDIAL MYOCARDIAL INFARCTION'
 'Other hypertrophic cardiomyopathy'
 'Conective and soft tissue of lower limb, including hip'
 'Connective and other soft tissue of lower limb, including hip'
 'Coxarthrosis' 'Coxarthrosis [arthrosis of hip]' 'Melaena (melena'
 'Other and unspecified abdominal pain' 'FRACTURE OF FEMUR'
 'MUSCLE STRAIN'
 'Hydronephrosis with renal and ureteral calculous obstruction'
 'Other and unspecified hydronephrosis'
 'Unspecified haematuria (kencing berdarah)'
 'Local infection of skin and subcutaneous tissue' 'Hyperlipidaemia'
 'Nontoxic multinodular goitre'
 'DIVERTICULAR DISEASE OF LARGE INTESTINE WITHOUT PERFORATION OR ABSCESS'
 'DYSPLASIA OF CERVIX UTERI, UNSPECIFIED'
 'RUPTURE OF LIGAMENTS AT ANKLE AND FOOT LEVEL' 'IMPACTED TEETH'
 'SEROUS RETINAL DETACHMENT' 'ABSCESS OF EXTERNAL EAR' 'CERVICALGIA'
 'OTHER SPECIFIED ABNORMAL UTERINE AND VAGINAL BLEEDING'
 'VERTIGINOUS SYNDROMES IN DISEASES CLASSIFIED ELSEWHERE'
 'NONPYOGENIC THROMBOSIS OF INTRACRANIAL VENOUS SYSTEM' 'DYSPNOEA'
 'BENIGN PAROXYSMAL VERTIGO' 'Degeneration of macula and posterior pole'
 'Primary open-angle glaucoma'
 'INFLUENZA DUE TO CERTAIN IDENTIFIED INFLUENZA VIRUS'
 'OTHER HYPERLIPIDAEMIA'
 'TYPE 1 DIABETES MELLITUS WITH PERIPHERAL CIRCULATORY COMPLICATIONS'
 'Atherosclerotic heart disease'
 'STIFFNESS OF JOINT, NOT ELSEWHERE CLASSIFIED'
 'POLYP OF FEMALE GENITAL TRACT' 'Other primary gonarthrosis'
 'GENERAL MEDICAL EXAMINATION' 'Cholelithiasis'
 'Viral Infection  Of Unspecified sites'
 'VIRAL INFECTION OF UNSPECIFIED SITE'
 'ANAEMIA DUE TO GLUCOSE-6-PHOSPHATE DEHYDROGENASE [G6PD] DEFICIENCY'
 'Dislocation , sprain and strain of joints and ligaments of knee'
 'Sprain and strain involving (anterior) (posterior) cruciate ligament of knee'
 'SPRAIN AND STRAIN INVOLVING (ANTERIOR)(POSTERIOR) CRUCIATE LIGAMENT OF KNEE'
 'Postprosedural disorders of eye and adnexa, not elsewhere classified'
 'ATRIAL FIBRILLATION AND FLUTTER' 'UNSPECIFIED DEMENTIA'
 'DISORDER OF KIDNEY AND URETER, UNSPECIFIED'
 'DISORDER OF GLOBE, UNSPECIFIED'
 'NEOPLASM OF UNCERTAIN OR UNKNOWN BEHAVIOUR, COLON'
 'OTHER SPECIFIED INTERVERTEBRAL DISC DISPLACEMENT'
 'LUMBAR AND OTHER INTERVERTEBRAL DISC DISORDERS WITH MYELOPATHY (G99.2*)'
 'CALCULUS OF GALLBLADDER WITH OTHER CHOLECYSTITIS'
 'MALIGNANT NEOPLASM OF LIVER AND INTRAHEPATIC BILE DUCTS'
 'ACUTE PHARYNGITIS'
 'CEREBRAL INFARCTION DUE TO THROMBOSIS OF PRECEREBRAL ARTERIES'
 'TRIGGER FINGER' 'CALCULUS OF KIDNEY AND URETER'
 'ANGINA PECTORIS, UNSPECIFIED' 'Breast, unspecified'
 'OTHER MALIGNANT NEOPLASMS OF SKIN' 'Sigmoid colon'
 'Malignant neoplasm of colon'
 'MALIGNANT NEOPLASM OF RECTOSIGMOID JUNCTION'
 'MALIGNANT NEOPLASM, SIGMOID COLON'
 'GASTRO-OESOPHAGEAL REFLUX DISEASE WITH OESOPHAGITIS'
 'URETHRAL STRICTURE, UNSPECIFIED' 'HYPERPLASIA OF PROSTATE'
 'EPIDERMAL CYST' 'CEREBRAL INFARCTION' 'CHOLELITHIASIS'
 'OPEN WOUND OF WRIST AND HAND'
 'Disrupti operation wound, not elsewhere classified'
 'ESSENTIAL (PRIMARY) HYPERTENSION'
 'Chronic laryngitis and laryngotracheitis' 'SECONDARY HYPERTENSION'
 'Acute Pharyngitis' 'FRACTURE OF RIB(S), STERNUM AND THORACIC SPINE'
 'OTHER DISORDERS OF EXTERNAL EAR' 'Unspecified urinary incontinence'
 'Postprocedural disorders of genitourinary system, Not Elsewhere Classified'
 'Bladder neck' 'BLADDER NECK OBSTRUCTION'
 'Other atresia and stenosis of urethra and bladder neck'
 'Injury  of Unspecified body region' 'CHRONIC ISCHAEMIC HEART DISEASE'
 'Lumbar and other intervertebral disc disorders with radiculopathy'
 'Dizziness and giddiness' 'Irritable bowel syndrome'
 'Primary gonarthrosis, bilateral'
 'MALIGNANT NEOPLASMA OF OTHER AND UNSPECIFIET MAJOR SALIVARY GLANDS'
 'CERVICOCRANIAL SYNDROME' 'Cervicocranial syndrome'
 'LUMBAR AND OTHER INTERVERTEBRAL DISC DISORDERS WITH RADICULOPATHY (G55.1*)'
 'Cellulitis' 'Middle ear, nasal cavity and accessory sinuses'
 'Other dorsalgia' 'SENILE CATARACT, UNSPECIFIED' 'HAEMORRHOIDS'
 'NON-INSULIN-DEPENDENT DIABETES MELLITUS' 'SENILE CATARACT' 'Pterygium'
 'Fracture of coccyx' 'Inguinal Hernia' 'Rectal polyp'
 'Polyp of corpus uteri' 'SPRAIN AND STRAIN OF ANKLE'
 'FRACTURE OF PATELLA' 'Hyperplasia of prostate' 'SYNCOPE AND COLLAPSE'
 'GASTRIC ULCER, UNSPECIFIED AS ACUTE OR CHRONIC, WITHOUT HAEMORRHAGE OR PERFORATION'
 'CARPAL TUNNEL SYNDROME' 'POLYCYTHAEMIA VERA'
 'Gastro-oesophageal reflux disease without oesophagitis'
 'VASCULAR HEADACHE, NOT ELSEWHERE CLASSIFIED'
 'OTHER AND UNSPECIFIED GASTROENTERITIS AND COLITIS OF INFECTIOUS ORIGIN'
 'ALLERGIC CONTACT DERMATITIS, UNSPECIFIED CAUSE' 'MELAENA' 'OESOPHAGITIS'
 'OTHER CERVICAL DISC DISORDERS' 'Spondylolisthesis' 'Spinal stenosis'
 'SPINAL STENOSIS, MULTIPLE SITES IN SPINE' 'INGUINAL HERNIA'
 'GASTRO-OESOPHAGEAL REFLUX DISEASE WITHOUT OESOPHAGITIS'
 'ESOPHAGITIS, UNSPECIFIED'
 'CUTANEOUS ABSCESS, FURUNCLE AND CARBUNCLE OF LIMB'
 'MALIGNANT NEOPLASM, BRONCHUS OR LUNG, UNSPECIFIED'
 'With other specified complcations' 'Other appendicitis'
 'ACUTE APPENDICITIS' 'Acute Appendicitis'
 'Epidermal cyst (kista epidermal)' 'ACUTE NASOPHARYNGITIS [COMMON COLD]'
 'LEIOMYOMA OF UTERUS' 'FISTULAE INVOLVING FEMALE GENITAL TRACT'
 'Syncope  And Collapse' 'CROHNS DISEASE [REGIONAL ENTERITIS]'
 'ULCERATIVE COLITIS' 'PAROXYSMAL TACHYCARDIA' 'OTHER DISEASES OF LIVER'
 'Other diseases of stomach and duodenum' 'ACIDOSIS'
 'Other primary coxarthrosis' 'OTHER GASTRITIS' 'Gastric Ulcer'
 'HYPO-OSMOLALITY AND HYPONATRAEMIA' 'Tuberculosis of lung'
 'OTHER SPECIFIED SPONDYLOPATHIES, CERVICAL REGION'
 'Injury of extensor muscle and tendon of other finger at wrist and hand level'
 'Traumatic rupture of lumbar invertebral disc'
 'MALIGNANT NEOPLASM OF RECTUM' 'NEUTROPENIA, UNSPECIFIED'
 'ANGINA PECTORIS' 'HEADACHE' 'Erosion and ectropion of cervix uteri'
 'LYMPHOID LEUKAEMIA' 'OTHER PERIPHERAL VERTIGO' 'SEBORRHOEIC KERATOSIS'
 'NONINFECTIVE GASTROENTERITIS AND COLITIS- UNSPECIFIED'
 'INJURY OF MUSCLE(S) AND TENDON(S) OF THE ROTATOR CUFF OF SHOULDER'
 'Postmenopausal bleeding' 'Endometrial adenomatous hyperplasia'
 'Benign neoplasm of breast' 'Cluster headache syndrome'
 'Cerebrovascular disease, unspecified' 'After-cataract (post cataract)'
 'Peripheral vascular disease, unspecified' 'Other idiopathic scoliosis'
 'Pseudopolyposis of colon' 'Venous insuffiency (chronic) (peripheral)'
 'Dyspepsia' 'Other autoimmune haemolytic anaemias'
 'MALIGNANT NEOPLASM OF PANCREAS' 'RETINAL DISORDER'
 'Clonic hemifacial spasm' 'Headache  ( Cephalgia)'
 'End-stage renal disease'
 'Other headache syndromes (sindrom sakit kepala)' 'Glaucoma suspect'
 'MALIGNANT NEOPLASM WITHOUT SPECIFICATION OF SITE'
 'Other senile cataract' 'Other specified diabetes mellitus'
 'Cervical disc disorder with myelopathy (G99.2*)' 'Colon'
 'ACUTE UPPER RESPIRATORY INFECTION' 'Other acute gastritis'
 'Oesophageal varices without bleeding'
 'Diverticular disease of large intestine without  perforation or abscess'
 'Subdural haemorrhagic'
 'Anaemia due other disorders of glutathione metabolism'
 'Pleural effusion' 'Impacted Teeth' 'OTHER DISEASE OF GALLBLADDER'
 'Gonathrosis, unspecified' 'DENGUE FEVER'
 'Embolism and thrombosis of unspecified vein'
 'Fracture of upper end of tibia' 'Pneumonia'
 'Other and unspec injuries of wrist and hand' 'ASTHMA'
 'Other synovitis and tenosynovitis'
 'Injury of muscle and tendon at wrist and hand level'
 'FATTY LIVER- NOT ELSEWHERE CLASSIFIED' 'Other bursitis of hip'
 'unspec lump in breast' 'HAEMORRHAGE OF ANUS AND RECTUM'
 'Corns and callosities (clavus)' 'Dysphasia and aphasia' 'Hypokalaemia'
 'DISEASE OF STOMACH AND DUODENUM- UNSPECIFIED' 'Cervical disc disoders'
 'Chronic gastritis' 'Connective and soft tissue,unspecified'
 'ALLERGIC RHINITIS' 'Cystitis'
 'Congestive heart failure (gagal jantung kongestif)' 'Cholecystitis'
 'Calcific tendinitis of shoulder' 'Bladder disorder, unspecified'
 'Dacryoadenitis'
 'Other disorders of eye and adnexa in diseases classified elsewhere'

In [7]:
data_claim.isna().sum()/data_claim.shape[0]*100 #persentase null per feature nya, klo misal lebih dari 30% apus aja columnya

Claim ID                         0.000000
Nomor Polis                      0.000000
Reimburse/Cashless               0.000000
Inpatient/Outpatient             0.799654
ICD Diagnosis                    0.129674
ICD Description                  0.129674
Status Klaim                     0.000000
Tanggal Pembayaran Klaim         0.799654
Tanggal Pasien Masuk RS          0.000000
Tanggal Pasien Keluar RS         0.000000
Nominal Klaim Yang Disetujui     0.000000
Nominal Biaya RS Yang Terjadi    0.000000
Lokasi RS                        0.151286
dtype: float64

In [8]:
data_claim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4627 entries, 0 to 4626
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Claim ID                       4627 non-null   object
 1   Nomor Polis                    4627 non-null   object
 2   Reimburse/Cashless             4627 non-null   object
 3   Inpatient/Outpatient           4590 non-null   object
 4   ICD Diagnosis                  4621 non-null   object
 5   ICD Description                4621 non-null   object
 6   Status Klaim                   4627 non-null   object
 7   Tanggal Pembayaran Klaim       4590 non-null   object
 8   Tanggal Pasien Masuk RS        4627 non-null   object
 9   Tanggal Pasien Keluar RS       4627 non-null   object
 10  Nominal Klaim Yang Disetujui   4627 non-null   float64
 11  Nominal Biaya RS Yang Terjadi  4627 non-null   float64
 12  Lokasi RS                      4620 non-null   object
dtypes: float64(2), object(11)
memory usage: 470.1+ KB

In [9]:
# pastikan datetime
data_claim['Tanggal Pasien Masuk RS'] = pd.to_datetime(
    data_claim['Tanggal Pasien Masuk RS']
)

# buat kolom tahun dan bulan dari tanggal masuk
data_claim['Tahun'] = data_claim['Tanggal Pasien Masuk RS'].dt.year
data_claim['Bulan'] = data_claim['Tanggal Pasien Masuk RS'].dt.month

# ambil minimum per claim dulu
data_claim['Claim_Dibayar'] = np.minimum(
    data_claim['Nominal Biaya RS Yang Terjadi'],
    data_claim['Nominal Klaim Yang Disetujui']
)

# group per bulan berdasarkan tanggal masuk
monthly = data_claim.groupby(['Tahun','Bulan']).agg(
    Number_of_Claims = ('Claim ID','count'),
    Total_Claim_Bulanan = ('Claim_Dibayar','sum'),
    Unique_Polis = ('Nomor Polis','nunique')
).reset_index()


# hasil akhir
final = monthly[['Tahun','Bulan','Number_of_Claims','Total_Claim_Bulanan', 'Unique_Polis']]

final.head()

   Tahun  Bulan  Number_of_Claims  Total_Claim_Bulanan  Unique_Polis
0   2024      1               302         2.012259e+10           179
1   2024      2               208         1.385533e+10           120
2   2024      3               278         1.430939e+10           174
3   2024      4               239         1.143551e+10           138
4   2024      5               263         1.216403e+10           152

In [10]:
final

    Tahun  Bulan  Number_of_Claims  Total_Claim_Bulanan  Unique_Polis
0    2024      1               302         2.012259e+10           179
1    2024      2               208         1.385533e+10           120
2    2024      3               278         1.430939e+10           174
3    2024      4               239         1.143551e+10           138
4    2024      5               263         1.216403e+10           152
5    2024      6               225         1.187225e+10           130
6    2024      7               257         1.492223e+10           142
7    2024      8               228         1.351294e+10           138
8    2024      9               208         1.226412e+10           121
9    2024     10               274         1.268117e+10           158
10   2024     11               270         1.373306e+10           147
11   2024     12               238         1.201391e+10           133
12   2025      1               216         9.610380e+09           132
13   2025      2               246         1.748054e+10           145
14   2025      3               230         1.367924e+10           126
15   2025      4               208         1.116425e+10           123
16   2025      5               239         1.222680e+10           142
17   2025      6               234         1.337312e+10           124
18   2025      7               264         1.369923e+10           147

XG BOOST

In [11]:
# pastikan urut waktu
final = final.sort_values(['Tahun','Bulan']).reset_index(drop=True)

final['date'] = pd.to_datetime(final['Tahun'].astype(str) + '-' + final['Bulan'].astype(str))
final = final.set_index('date')

targets = [
    'Number_of_Claims',
    'Total_Claim_Bulanan',
    'Unique_Polis'
]

In [12]:
def create_lags(data, target, n_lags):
    df = data[[target]].copy()
    for i in range(1, n_lags+1):
        df[f'lag_{i}'] = df[target].shift(i)
    return df.dropna()

In [13]:
def train_and_forecast(ts, target):

    tscv = TimeSeriesSplit(n_splits=3)
    results = {}
    
    # cari lag terbaik
    for lag in range(1,7):
        df_lag = create_lags(ts, target, lag)
        
        X = df_lag.drop(columns=[target])
        y = df_lag[target]
        
        rmse_list = []
        
        for train_idx, test_idx in tscv.split(X):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
            
            model = XGBRegressor(
                n_estimators=200,
                max_depth=3,
                learning_rate=0.05,
                random_state=42
            )
            
            model.fit(X_train, y_train)
            preds = model.predict(X_test)
            rmse = np.sqrt(mean_squared_error(y_test, preds))
            rmse_list.append(rmse)
        
        results[lag] = np.mean(rmse_list)
    
    best_lag = min(results, key=results.get)
    
    # train final model
    df_lag = create_lags(ts, target, best_lag)
    X = df_lag.drop(columns=[target])
    y = df_lag[target]
    
    model = XGBRegressor(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        random_state=42
    )
    
    model.fit(X, y)
    
    # forecasting 5 bulan ke depan
    future_preds = []
    last_data = ts[[target]].copy()
    
    for i in range(5):
        df_temp = create_lags(last_data, target, best_lag)
        last_row = df_temp.iloc[-1:]
        
        X_pred = last_row.drop(columns=[target])
        pred = model.predict(X_pred)[0]
        
        # bulatkan untuk count data
        if target in ['Number_of_Claims','Unique_Polis']:
            pred = round(pred)
        
        future_preds.append(pred)
        
        next_month = last_data.index[-1] + pd.DateOffset(months=1)
        last_data.loc[next_month] = pred
    
    return best_lag, future_preds

In [14]:
forecast_dict = {}
lag_dict = {}

for target in targets:
    best_lag, preds = train_and_forecast(final, target)
    forecast_dict[target] = preds
    lag_dict[target] = best_lag

print("Best Lag per Target:", lag_dict)

future_dates = pd.date_range(start='2025-08-01', periods=5, freq='MS')

forecast_df = pd.DataFrame({
    'Date': future_dates,
    'Predicted_Number_of_Claims': forecast_dict['Number_of_Claims'],
    'Predicted_Total_Claim': forecast_dict['Total_Claim_Bulanan'],
    'Predicted_Unique_Polis': forecast_dict['Unique_Polis']
})

forecast_df

Best Lag per Target: {'Number_of_Claims': 5, 'Total_Claim_Bulanan': 6, 'Unique_Polis': 6}

,Date,Predicted_Number_of_Claims,Predicted_Total_Claim,Predicted_Unique_Polis
0,2025-08-01,264,1.369914e+10,147
1,2025-09-01,238,1.057042e+10,146
2,2025-10-01,231,1.219987e+10,137
3,2025-11-01,216,1.410730e+10,139
4,2025-12-01,242,1.343775e+10,143

In [15]:
forecast_df['Predicted_Claim_Frequency'] = (
    forecast_df['Predicted_Number_of_Claims'] /
    forecast_df['Predicted_Unique_Polis']
) * 100

forecast_df['Predicted_Claim_Severity'] = (
    forecast_df['Predicted_Total_Claim'] /
    forecast_df['Predicted_Number_of_Claims']
)

In [16]:
forecast_df

,Date,Predicted_Number_of_Claims,Predicted_Total_Claim,Predicted_Unique_Polis,Predicted_Claim_Frequency,Predicted_Claim_Severity
0,2025-08-01,264,1.369914e+10,147,179.591837,5.189067e+07
1,2025-09-01,238,1.057042e+10,146,163.013699,4.441352e+07
2,2025-10-01,231,1.219987e+10,137,168.613139,5.281329e+07
3,2025-11-01,216,1.410730e+10,139,155.395683,6.531158e+07
4,2025-12-01,242,1.343775e+10,143,169.230769,5.552789e+07

**Conclusion : dapet MAPE : 15.59937**

Random Forest

In [17]:
from sklearn.ensemble import RandomForestRegressor

In [18]:
def train_and_forecast_rf(ts, target):

    tscv = TimeSeriesSplit(n_splits=3)
    results = {}
    
    # cari lag terbaik
    for lag in range(1,7):
        df_lag = create_lags(ts, target, lag)
        
        X = df_lag.drop(columns=[target])
        y = df_lag[target]
        
        rmse_list = []
        
        for train_idx, test_idx in tscv.split(X):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
            
            model = RandomForestRegressor(
                n_estimators=300,
                max_depth=5,
                random_state=42
            )
            
            model.fit(X_train, y_train)
            preds = model.predict(X_test)
            rmse = np.sqrt(mean_squared_error(y_test, preds))
            rmse_list.append(rmse)
        
        results[lag] = np.mean(rmse_list)
    
    best_lag = min(results, key=results.get)
    
    # train final model
    df_lag = create_lags(ts, target, best_lag)
    X = df_lag.drop(columns=[target])
    y = df_lag[target]
    
    model = RandomForestRegressor(
        n_estimators=400,
        max_depth=5,
        random_state=42
    )
    
    model.fit(X, y)
    
    # forecasting 5 bulan ke depan
    future_preds = []
    last_data = ts[[target]].copy()
    
    for i in range(5):
        df_temp = create_lags(last_data, target, best_lag)
        last_row = df_temp.iloc[-1:]
        
        X_pred = last_row.drop(columns=[target])
        pred = model.predict(X_pred)[0]
        
        if target in ['Number_of_Claims','Unique_Polis']:
            pred = round(pred)
        
        future_preds.append(pred)
        
        next_month = last_data.index[-1] + pd.DateOffset(months=1)
        last_data.loc[next_month] = pred
    
    return best_lag, future_preds

In [19]:
forecast_dict = {}
lag_dict = {}

for target in targets:
    best_lag, preds = train_and_forecast_rf(final, target)
    forecast_dict[target] = preds
    lag_dict[target] = best_lag

print("Best Lag per Target:", lag_dict)

future_dates = pd.date_range(start='2025-08-01', periods=5, freq='MS')

forecast_df_rf = pd.DataFrame({
    'Date': future_dates,
    'Predicted_Number_of_Claims': forecast_dict['Number_of_Claims'],
    'Predicted_Total_Claim': forecast_dict['Total_Claim_Bulanan'],
    'Predicted_Unique_Polis': forecast_dict['Unique_Polis']
})

forecast_df_rf

Best Lag per Target: {'Number_of_Claims': 4, 'Total_Claim_Bulanan': 2, 'Unique_Polis': 4}

,Date,Predicted_Number_of_Claims,Predicted_Total_Claim,Predicted_Unique_Polis
0,2025-08-01,247,1.362824e+10,141
1,2025-09-01,232,1.202455e+10,138
2,2025-10-01,227,1.164754e+10,131
3,2025-11-01,222,1.122594e+10,136
4,2025-12-01,234,1.406110e+10,137

In [20]:
forecast_df_rf['Predicted_Claim_Frequency'] = (
    forecast_df_rf['Predicted_Number_of_Claims'] /
    forecast_df_rf['Predicted_Unique_Polis']
) * 100

forecast_df_rf['Predicted_Claim_Severity'] = (
    forecast_df_rf['Predicted_Total_Claim'] /
    forecast_df_rf['Predicted_Number_of_Claims']
)

In [21]:
forecast_df_rf

,Date,Predicted_Number_of_Claims,Predicted_Total_Claim,Predicted_Unique_Polis,Predicted_Claim_Frequency,Predicted_Claim_Severity
0,2025-08-01,247,1.362824e+10,141,175.177305,5.517505e+07
1,2025-09-01,232,1.202455e+10,138,168.115942,5.182997e+07
2,2025-10-01,227,1.164754e+10,131,173.282443,5.131074e+07
3,2025-11-01,222,1.122594e+10,136,163.235294,5.056731e+07
4,2025-12-01,234,1.406110e+10,137,170.802920,6.009017e+07

MAPE : 21.17863

SARIMAX

In [22]:
import warnings
warnings.filterwarnings("ignore")
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_squared_error

In [23]:
def train_sarima(ts, target):

    y = ts[target].asfreq('MS')  # monthly start frequency
    
    # parameter kecil dulu biar cepat
    p = d = q = range(0, 2)
    P = D = Q = range(0, 2)
    s = 12  # seasonality bulanan
    
    best_aic = np.inf
    best_order = None
    best_seasonal = None
    
    for i in p:
        for j in d:
            for k in q:
                for sp in P:
                    for sd in D:
                        for sq in Q:
                            try:
                                model = SARIMAX(
                                    y,
                                    order=(i,j,k),
                                    seasonal_order=(sp,sd,sq,s),
                                    enforce_stationarity=False,
                                    enforce_invertibility=False
                                )
                                results = model.fit(disp=False)
                                
                                if results.aic < best_aic:
                                    best_aic = results.aic
                                    best_order = (i,j,k)
                                    best_seasonal = (sp,sd,sq,s)
                            except:
                                continue

    print(f"Best Order for {target}: {best_order}")
    print(f"Best Seasonal Order: {best_seasonal}")
    
    # Train final model
    model = SARIMAX(
        y,
        order=best_order,
        seasonal_order=best_seasonal,
        enforce_stationarity=False,
        enforce_invertibility=False
    )
    
    results = model.fit(disp=False)
    
    # Forecast 5 bulan
    forecast = results.forecast(steps=5)
    
    # bulatkan untuk count
    if target in ['Number_of_Claims','Unique_Polis']:
        forecast = forecast.round()
    
    return forecast

In [24]:
forecast_sarima = {}

for target in targets:
    preds = train_sarima(final, target)
    forecast_sarima[target] = preds.values

future_dates = pd.date_range(start=final.index[-1] + pd.DateOffset(months=1),
                             periods=5, freq='MS')

forecast_df_sarima = pd.DataFrame({
    'Date': future_dates,
    'Predicted_Number_of_Claims': forecast_sarima['Number_of_Claims'],
    'Predicted_Total_Claim': forecast_sarima['Total_Claim_Bulanan'],
    'Predicted_Unique_Polis': forecast_sarima['Unique_Polis']
})

forecast_df_sarima

c:\Users\hi\anaconda3\envs\data_science\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Best Order for Number_of_Claims: (0, 0, 0)
Best Seasonal Order: (0, 1, 1, 12)

c:\Users\hi\anaconda3\envs\data_science\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
c:\Users\hi\anaconda3\envs\data_science\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
c:\Users\hi\anaconda3\envs\data_science\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Best Order for Total_Claim_Bulanan: (0, 0, 0)
Best Seasonal Order: (0, 1, 1, 12)

c:\Users\hi\anaconda3\envs\data_science\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Best Order for Unique_Polis: (0, 0, 0)
Best Seasonal Order: (0, 1, 1, 12)

,Date,Predicted_Number_of_Claims,Predicted_Total_Claim,Predicted_Unique_Polis
0,2025-08-01,228.0,1.351294e+10,138.0
1,2025-09-01,208.0,1.226412e+10,121.0
2,2025-10-01,274.0,1.268117e+10,158.0
3,2025-11-01,270.0,1.373306e+10,147.0
4,2025-12-01,238.0,1.201391e+10,133.0

In [25]:
forecast_df_sarima['Predicted_Claim_Frequency'] = (
    forecast_df_sarima['Predicted_Number_of_Claims'] /
    forecast_df_sarima['Predicted_Unique_Polis']
) * 100

forecast_df_sarima['Predicted_Claim_Severity'] = (
    forecast_df_sarima['Predicted_Total_Claim'] /
    forecast_df_sarima['Predicted_Number_of_Claims']
)

In [26]:
forecast_df_sarima

,Date,Predicted_Number_of_Claims,Predicted_Total_Claim,Predicted_Unique_Polis,Predicted_Claim_Frequency,Predicted_Claim_Severity
0,2025-08-01,228.0,1.351294e+10,138.0,165.217391,5.926726e+07
1,2025-09-01,208.0,1.226412e+10,121.0,171.900826,5.896211e+07
2,2025-10-01,274.0,1.268117e+10,158.0,173.417722,4.628163e+07
3,2025-11-01,270.0,1.373306e+10,147.0,183.673469,5.086318e+07
4,2025-12-01,238.0,1.201391e+10,133.0,178.947368,5.047861e+07

In [27]:
# Make sure Date column is datetime
forecast_df_sarima["Date"] = pd.to_datetime(forecast_df_sarima["Date"])

submission_rows = []

for _, row in forecast_df_sarima.iterrows():
    
    year = row["Date"].year
    month = f"{row['Date'].month:02d}"
    
    submission_rows.append(
        (f"{year}_{month}_Claim_Frequency", row["Predicted_Claim_Frequency"])
    )
    submission_rows.append(
        (f"{year}_{month}_Claim_Severity", row["Predicted_Claim_Severity"])
    )
    submission_rows.append(
        (f"{year}_{month}_Total_Claim", row["Predicted_Total_Claim"])
    )

submission_df = pd.DataFrame(submission_rows, columns=["id", "value"])

# Optional: remove scientific notation for severity/total
submission_df["value"] = submission_df["value"].astype(float)

# Export to CSV
submission_df.to_csv("submission_sarima.csv", index=False)

print("submission_sarima.csv created successfully")

submission_sarima.csv created successfully