In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Data Preprocessing

In [3]:
# 1. LOAD THE DATA
# Note: You accidentally loaded Data_Klaim twice in your prompt. I fixed the second one.
claims_df = pd.read_csv('data/Data_Klaim.csv')
polis_df = pd.read_csv('data/Data_Polis.csv')

In [4]:
claims_df.head()

,Claim ID,Nomor Polis,Reimburse/Cashless,Inpatient/Outpatient,ICD Diagnosis,ICD Description,Status Klaim,Tanggal Pembayaran Klaim,Tanggal Pasien Masuk RS,Tanggal Pasien Keluar RS,Nominal Klaim Yang Disetujui,Nominal Biaya RS Yang Terjadi,Lokasi RS
0,C-0001-M,POL-0176,R,OP,C50,MALIGNANT NEOPLASM OF BREAST,PAID,2024-07-08,2024-05-27,2024-05-27,28093653.0,6.143948e+06,Singapore
1,C-0002-M,POL-3288,R,OP,C34,MALIGNANT NEOPLASM OF BRONCHUS AND LUNG,PAID,2024-08-06,2024-07-15,2024-07-15,80987278.0,8.230952e+07,Malaysia
2,C-0003-M,POL-1786,R,OP,C18.9,"MALIGNANT NEOPLASM, COLON, UNSPECIFIED",PAID,2024-10-17,2024-05-16,2024-05-16,183047130.0,1.928599e+08,Singapore
3,C-0004-M,POL-1786,R,OP,C34,MALIGNANT NEOPLASM OF BRONCHUS AND LUNG,PAID,2024-09-03,2024-07-18,2024-07-18,191424386.0,1.914244e+08,Singapore
4,C-0005-M,POL-2778,R,OP,C50,MALIGNANT NEOPLASM OF BREAST,PAID,NaN,2024-06-06,2024-06-06,138936357.0,1.389364e+08,Singapore

In [5]:
polis_df.head()

  Nomor Polis Plan Code Gender  Tanggal Lahir  Tanggal Efektif Polis Domisili
0    POL-0001     M-003      M       19640811               20140603  JAKARTA
1    POL-0002     M-003      M       19710730               20140603  JAKARTA
2    POL-0003     M-001      M       19790821               20160808  JAKARTA
3    POL-0004     M-003      M       20140724               20160811  JAKARTA
4    POL-0005     M-001      F       19810114               20150828  JAKARTA

In [6]:
# 2. CALCULATE EXPOSURE FROM POLIS TABLE (CRITICAL FOR FREQUENCY)
# Convert Tanggal Efektif Polis (format YYYYMMDD) to datetime
polis_df['Tanggal Efektif Polis'] = pd.to_datetime(polis_df['Tanggal Efektif Polis'], format='%Y%m%d', errors='coerce')
polis_df.head()

  Nomor Polis Plan Code Gender  Tanggal Lahir Tanggal Efektif Polis Domisili
0    POL-0001     M-003      M       19640811            2014-06-03  JAKARTA
1    POL-0002     M-003      M       19710730            2014-06-03  JAKARTA
2    POL-0003     M-001      M       19790821            2016-08-08  JAKARTA
3    POL-0004     M-003      M       20140724            2016-08-11  JAKARTA
4    POL-0005     M-001      F       19810114            2015-08-28  JAKARTA

In [7]:
# Get min start date and max claim date to build a full timeline
min_date = polis_df['Tanggal Efektif Polis'].min()
claims_df['Tanggal Pasien Masuk RS'] = pd.to_datetime(claims_df['Tanggal Pasien Masuk RS'], errors='coerce')
max_date = claims_df['Tanggal Pasien Masuk RS'].max()

print(min_date)
print(max_date)

2011-12-05 00:00:00
2025-07-31 00:00:00

In [8]:
# Create a continuous monthly timeline and calculate cumulative active policies
all_months = pd.period_range(start=min_date, end=max_date, freq='M')
exposure_df = pd.DataFrame({'Period': all_months})
exposure_df.head()

    Period
0  2011-12
1  2012-01
2  2012-02
3  2012-03
4  2012-04

In [9]:
# Count how many new policies started each month
polis_df['Period'] = polis_df['Tanggal Efektif Polis'].dt.to_period('M')
monthly_sales = polis_df.groupby('Period').size().reset_index(name='New_Policies')
monthly_sales.head()

    Period  New_Policies
0  2011-12            42
1  2012-01            28
2  2012-02            46
3  2012-03            57
4  2012-04            41

In [10]:
# Merge timeline with sales and calculate cumulative exposure
exposure_df = pd.merge(exposure_df, monthly_sales, on='Period', how='left')
exposure_df['New_Policies'] = exposure_df['New_Policies'].fillna(0)
exposure_df['Exposure'] = exposure_df['New_Policies'].cumsum() # Total Active Policies
exposure_df.head()

    Period  New_Policies  Exposure
0  2011-12          42.0      42.0
1  2012-01          28.0      70.0
2  2012-02          46.0     116.0
3  2012-03          57.0     173.0
4  2012-04          41.0     214.0

In [11]:
# 3. PREPARE & SORT CLAIMS DATA
# Sort by Tanggal Pasien Masuk RS as requested
claims_df = claims_df.sort_values('Tanggal Pasien Masuk RS')
claims_df.head()

,Claim ID,Nomor Polis,Reimburse/Cashless,Inpatient/Outpatient,ICD Diagnosis,ICD Description,Status Klaim,Tanggal Pembayaran Klaim,Tanggal Pasien Masuk RS,Tanggal Pasien Keluar RS,Nominal Klaim Yang Disetujui,Nominal Biaya RS Yang Terjadi,Lokasi RS
2810,C-3627-M,POL-3872,C,IP,B34.2,"CORONAVIRUS INFECTION, UNSPECIFIED SITE",PAID,2024-04-25,2024-01-01,2024-01-07,14741310.0,15025749.0,Indonesia
3006,C-3836-M,POL-2078,C,OP,N18.5,"CHRONIC KIDNEY DISEASE, STAGE 5",PAID,2024-04-05,2024-01-02,2024-01-02,2769687.0,3400335.0,Indonesia
2816,C-3636-M,POL-3932,C,IP,H82,VERTIGINOUS SYNDROMES IN DISEASES CLASSIFIED E...,PAID,2024-02-06,2024-01-02,2024-01-07,36417500.0,36417500.0,Indonesia
1948,C-2519-M,POL-2436,R,IP,H35,OTHER RETINAL DISORDERS,PAID,2024-01-17,2024-01-02,2024-01-02,15667000.0,15667000.0,Indonesia
144,C-0245-M,POL-2200,C,OP,N23,UNSPECIFIED RENAL COLIC,PAID,2024-04-25,2024-01-02,2024-01-02,1839000.0,1870000.0,Indonesia

In [12]:
# Extract Month, Year, and Period for grouping
claims_df['Year'] = claims_df['Tanggal Pasien Masuk RS'].dt.year
claims_df['Month'] = claims_df['Tanggal Pasien Masuk RS'].dt.month
claims_df['Period'] = claims_df['Tanggal Pasien Masuk RS'].dt.to_period('M')
claims_df.head()

,Claim ID,Nomor Polis,Reimburse/Cashless,Inpatient/Outpatient,ICD Diagnosis,ICD Description,Status Klaim,Tanggal Pembayaran Klaim,Tanggal Pasien Masuk RS,Tanggal Pasien Keluar RS,Nominal Klaim Yang Disetujui,Nominal Biaya RS Yang Terjadi,Lokasi RS,Year,Month,Period
2810,C-3627-M,POL-3872,C,IP,B34.2,"CORONAVIRUS INFECTION, UNSPECIFIED SITE",PAID,2024-04-25,2024-01-01,2024-01-07,14741310.0,15025749.0,Indonesia,2024,1,2024-01
3006,C-3836-M,POL-2078,C,OP,N18.5,"CHRONIC KIDNEY DISEASE, STAGE 5",PAID,2024-04-05,2024-01-02,2024-01-02,2769687.0,3400335.0,Indonesia,2024,1,2024-01
2816,C-3636-M,POL-3932,C,IP,H82,VERTIGINOUS SYNDROMES IN DISEASES CLASSIFIED E...,PAID,2024-02-06,2024-01-02,2024-01-07,36417500.0,36417500.0,Indonesia,2024,1,2024-01
1948,C-2519-M,POL-2436,R,IP,H35,OTHER RETINAL DISORDERS,PAID,2024-01-17,2024-01-02,2024-01-02,15667000.0,15667000.0,Indonesia,2024,1,2024-01
144,C-0245-M,POL-2200,C,OP,N23,UNSPECIFIED RENAL COLIC,PAID,2024-04-25,2024-01-02,2024-01-02,1839000.0,1870000.0,Indonesia,2024,1,2024-01

In [13]:
# Identify Inpatient (IP) vs Outpatient (OP, ODC, ODS)
claims_df['Is_IP'] = claims_df['Inpatient/Outpatient'].isin(['IP']).astype(int)
claims_df['Is_OP'] = claims_df['Inpatient/Outpatient'].isin(['OP', 'ODC', 'ODS']).astype(int)
claims_df.head()

,Claim ID,Nomor Polis,Reimburse/Cashless,Inpatient/Outpatient,ICD Diagnosis,ICD Description,Status Klaim,Tanggal Pembayaran Klaim,Tanggal Pasien Masuk RS,Tanggal Pasien Keluar RS,Nominal Klaim Yang Disetujui,Nominal Biaya RS Yang Terjadi,Lokasi RS,Year,Month,Period,Is_IP,Is_OP
2810,C-3627-M,POL-3872,C,IP,B34.2,"CORONAVIRUS INFECTION, UNSPECIFIED SITE",PAID,2024-04-25,2024-01-01,2024-01-07,14741310.0,15025749.0,Indonesia,2024,1,2024-01,1,0
3006,C-3836-M,POL-2078,C,OP,N18.5,"CHRONIC KIDNEY DISEASE, STAGE 5",PAID,2024-04-05,2024-01-02,2024-01-02,2769687.0,3400335.0,Indonesia,2024,1,2024-01,0,1
2816,C-3636-M,POL-3932,C,IP,H82,VERTIGINOUS SYNDROMES IN DISEASES CLASSIFIED E...,PAID,2024-02-06,2024-01-02,2024-01-07,36417500.0,36417500.0,Indonesia,2024,1,2024-01,1,0
1948,C-2519-M,POL-2436,R,IP,H35,OTHER RETINAL DISORDERS,PAID,2024-01-17,2024-01-02,2024-01-02,15667000.0,15667000.0,Indonesia,2024,1,2024-01,1,0
144,C-0245-M,POL-2200,C,OP,N23,UNSPECIFIED RENAL COLIC,PAID,2024-04-25,2024-01-02,2024-01-02,1839000.0,1870000.0,Indonesia,2024,1,2024-01,0,1

In [15]:
# 4. AGGREGATE PER MONTH
agg_df = claims_df.groupby(['Period', 'Year', 'Month']).agg(
    Jumlah_Inpatient=('Is_IP', 'sum'),
    Jumlah_Outpatient=('Is_OP', 'sum'),
    Jumlah_Klaim=('Claim ID', 'count'),
    Total_Nominal_Klaim=('Nominal Klaim Yang Disetujui', 'sum')
).reset_index()
agg_df.head()

,Period,Year,Month,Jumlah_Inpatient,Jumlah_Outpatient,Jumlah_Klaim,Total_Nominal_Klaim
0,2024-01,2024,1,213,81,302,2.026098e+10
1,2024-02,2024,2,140,60,208,1.385965e+10
2,2024-03,2024,3,196,82,278,1.431126e+10
3,2024-04,2024,4,160,79,239,1.144106e+10
4,2024-05,2024,5,163,100,263,1.221146e+10

In [16]:
# 5. MERGE CLAIMS WITH EXPOSURE & CALCULATE METRICS
final_df = pd.merge(agg_df, exposure_df[['Period', 'Exposure']], on='Period', how='left')
final_df.head()

,Period,Year,Month,Jumlah_Inpatient,Jumlah_Outpatient,Jumlah_Klaim,Total_Nominal_Klaim,Exposure
0,2024-01,2024,1,213,81,302,2.026098e+10,4096.0
1,2024-02,2024,2,140,60,208,1.385965e+10,4096.0
2,2024-03,2024,3,196,82,278,1.431126e+10,4096.0
3,2024-04,2024,4,160,79,239,1.144106e+10,4096.0
4,2024-05,2024,5,163,100,263,1.221146e+10,4096.0

In [17]:
# Metric 1: Ratio Inpatient / Outpatient (using np.where to avoid divide-by-zero errors)
final_df['Ratio Inpatient / Outpatient'] = np.where(
    final_df['Jumlah_Outpatient'] == 0, 
    np.nan, 
    final_df['Jumlah_Inpatient'] / final_df['Jumlah_Outpatient']
)
final_df.head()

,Period,Year,Month,Jumlah_Inpatient,Jumlah_Outpatient,Jumlah_Klaim,Total_Nominal_Klaim,Exposure,Ratio Inpatient / Outpatient
0,2024-01,2024,1,213,81,302,2.026098e+10,4096.0,2.629630
1,2024-02,2024,2,140,60,208,1.385965e+10,4096.0,2.333333
2,2024-03,2024,3,196,82,278,1.431126e+10,4096.0,2.390244
3,2024-04,2024,4,160,79,239,1.144106e+10,4096.0,2.025316
4,2024-05,2024,5,163,100,263,1.221146e+10,4096.0,1.630000

In [18]:
# Metric 2: True Frequency Rate = (Jumlah Klaim / Active Policies)
final_df['Freq_Rate'] = final_df['Jumlah_Klaim'] / final_df['Exposure']
final_df.head()

,Period,Year,Month,Jumlah_Inpatient,Jumlah_Outpatient,Jumlah_Klaim,Total_Nominal_Klaim,Exposure,Ratio Inpatient / Outpatient,Freq_Rate
0,2024-01,2024,1,213,81,302,2.026098e+10,4096.0,2.629630,0.073730
1,2024-02,2024,2,140,60,208,1.385965e+10,4096.0,2.333333,0.050781
2,2024-03,2024,3,196,82,278,1.431126e+10,4096.0,2.390244,0.067871
3,2024-04,2024,4,160,79,239,1.144106e+10,4096.0,2.025316,0.058350
4,2024-05,2024,5,163,100,263,1.221146e+10,4096.0,1.630000,0.064209

In [19]:
# Metric 3: Severity = (Total Nominal / Jumlah Klaim)
final_df['Severity'] = final_df['Total_Nominal_Klaim'] / final_df['Jumlah_Klaim']
final_df.head()

,Period,Year,Month,Jumlah_Inpatient,Jumlah_Outpatient,Jumlah_Klaim,Total_Nominal_Klaim,Exposure,Ratio Inpatient / Outpatient,Freq_Rate,Severity
0,2024-01,2024,1,213,81,302,2.026098e+10,4096.0,2.629630,0.073730,6.708934e+07
1,2024-02,2024,2,140,60,208,1.385965e+10,4096.0,2.333333,0.050781,6.663291e+07
2,2024-03,2024,3,196,82,278,1.431126e+10,4096.0,2.390244,0.067871,5.147935e+07
3,2024-04,2024,4,160,79,239,1.144106e+10,4096.0,2.025316,0.058350,4.787056e+07
4,2024-05,2024,5,163,100,263,1.221146e+10,4096.0,1.630000,0.064209,4.643141e+07

In [20]:
# 6. CLEAN UP AND RENAME COLUMNS
final_df = final_df[[
    'Period','Month', 'Year', 'Jumlah_Inpatient', 'Jumlah_Outpatient', 
    'Ratio Inpatient / Outpatient', 'Exposure', 'Jumlah_Klaim', 'Freq_Rate', 'Severity', 'Total_Nominal_Klaim'
]].copy()
final_df.head()

,Period,Month,Year,Jumlah_Inpatient,Jumlah_Outpatient,Ratio Inpatient / Outpatient,Exposure,Jumlah_Klaim,Freq_Rate,Severity,Total_Nominal_Klaim
0,2024-01,1,2024,213,81,2.629630,4096.0,302,0.073730,6.708934e+07,2.026098e+10
1,2024-02,2,2024,140,60,2.333333,4096.0,208,0.050781,6.663291e+07,1.385965e+10
2,2024-03,3,2024,196,82,2.390244,4096.0,278,0.067871,5.147935e+07,1.431126e+10
3,2024-04,4,2024,160,79,2.025316,4096.0,239,0.058350,4.787056e+07,1.144106e+10
4,2024-05,5,2024,163,100,1.630000,4096.0,263,0.064209,4.643141e+07,1.221146e+10

In [21]:
final_df = final_df.rename(columns={
    'Jumlah_Inpatient': 'Jumlah Inpatient',
    'Jumlah_Outpatient': 'Jumlah Outpatient',
    'Jumlah_Klaim': 'Frequency',
    'Total_Nominal_Klaim': 'Total Nominal Klaim'
})
final_df.head()

,Period,Month,Year,Jumlah Inpatient,Jumlah Outpatient,Ratio Inpatient / Outpatient,Exposure,Frequency,Freq_Rate,Severity,Total Nominal Klaim
0,2024-01,1,2024,213,81,2.629630,4096.0,302,0.073730,6.708934e+07,2.026098e+10
1,2024-02,2,2024,140,60,2.333333,4096.0,208,0.050781,6.663291e+07,1.385965e+10
2,2024-03,3,2024,196,82,2.390244,4096.0,278,0.067871,5.147935e+07,1.431126e+10
3,2024-04,4,2024,160,79,2.025316,4096.0,239,0.058350,4.787056e+07,1.144106e+10
4,2024-05,5,2024,163,100,1.630000,4096.0,263,0.064209,4.643141e+07,1.221146e+10

In [22]:

# Add Final "Total Klaim" column as requested
final_df['Total Klaim'] = final_df['Total Nominal Klaim']

# Remove any empty rows where date couldn't be parsed
final_df = final_df.dropna(subset=['Year', 'Month']).copy()
final_df['Year'] = final_df['Year'].astype(int)
final_df['Month'] = final_df['Month'].astype(int)
final_df.head()

,Period,Month,Year,Jumlah Inpatient,Jumlah Outpatient,Ratio Inpatient / Outpatient,Exposure,Frequency,Freq_Rate,Severity,Total Nominal Klaim,Total Klaim
0,2024-01,1,2024,213,81,2.629630,4096.0,302,0.073730,6.708934e+07,2.026098e+10,2.026098e+10
1,2024-02,2,2024,140,60,2.333333,4096.0,208,0.050781,6.663291e+07,1.385965e+10,1.385965e+10
2,2024-03,3,2024,196,82,2.390244,4096.0,278,0.067871,5.147935e+07,1.431126e+10,1.431126e+10
3,2024-04,4,2024,160,79,2.025316,4096.0,239,0.058350,4.787056e+07,1.144106e+10,1.144106e+10
4,2024-05,5,2024,163,100,1.630000,4096.0,263,0.064209,4.643141e+07,1.221146e+10,1.221146e+10

In [23]:
final_df

,Period,Month,Year,Jumlah Inpatient,Jumlah Outpatient,Ratio Inpatient / Outpatient,Exposure,Frequency,Freq_Rate,Severity,Total Nominal Klaim,Total Klaim
0,2024-01,1,2024,213,81,2.629630,4096.0,302,0.073730,6.708934e+07,2.026098e+10,2.026098e+10
1,2024-02,2,2024,140,60,2.333333,4096.0,208,0.050781,6.663291e+07,1.385965e+10,1.385965e+10
2,2024-03,3,2024,196,82,2.390244,4096.0,278,0.067871,5.147935e+07,1.431126e+10,1.431126e+10
3,2024-04,4,2024,160,79,2.025316,4096.0,239,0.058350,4.787056e+07,1.144106e+10,1.144106e+10
4,2024-05,5,2024,163,100,1.630000,4096.0,263,0.064209,4.643141e+07,1.221146e+10,1.221146e+10
5,2024-06,6,2024,106,119,0.890756,4096.0,225,0.054932,5.388963e+07,1.212517e+10,1.212517e+10
6,2024-07,7,2024,112,144,0.777778,4096.0,257,0.062744,5.825104e+07,1.497052e+10,1.497052e+10
7,2024-08,8,2024,95,130,0.730769,4096.0,228,0.055664,5.926726e+07,1.351294e+10,1.351294e+10
8,2024-09,9,2024,89,117,0.760684,4096.0,208,0.050781,5.896211e+07,1.226412e+10,1.226412e+10
9,2024-10,10,2024,107,164,0.652439,4096.0,274,0.066895,4.628163e+07,1.268117e+10,1.268117e+10
10,2024-11,11,2024,97,172,0.563953,4096.0,270,0.065918,5.086318e+07,1.373306e+10,1.373306e+10
11,2024-12,12,2024,90,142,0.633803,4096.0,238,0.058105,5.047861e+07,1.201391e+10,1.201391e+10
12,2025-01,1,2025,101,112,0.901786,4096.0,216,0.052734,4.449250e+07,9.610380e+09,9.610380e+09
13,2025-02,2,2025,107,137,0.781022,4096.0,246,0.060059,7.105911e+07,1.748054e+10,1.748054e+10
14,2025-03,3,2025,84,146,0.575342,4096.0,230,0.056152,5.947496e+07,1.367924e+10,1.367924e+10
15,2025-04,4,2025,82,126,0.650794,4096.0,208,0.050781,5.367427e+07,1.116425e+10,1.116425e+10
16,2025-05,5,2025,98,141,0.695035,4096.0,239,0.058350,5.115814e+07,1.222680e+10,1.222680e+10
17,2025-06,6,2025,91,143,0.636364,4096.0,234,0.057129,5.715008e+07,1.337312e+10,1.337312e+10
18,2025-07,7,2025,127,137,0.927007,4096.0,264,0.064453,5.189101e+07,1.369923e+10,1.369923e+10

GBR

In [24]:
from sklearn.ensemble import GradientBoostingRegressor

In [25]:
def create_lag_features(data, target_col):
    df_feat = data.copy()
    # Lag Features (1, 2, 3 months back)
    for lag in [1, 2, 3]:
        df_feat[f'lag_{lag}'] = df_feat[target_col].shift(lag)
    # Rolling Feature (Mean of last 3 months)
    df_feat['rolling_mean_3'] = df_feat[target_col].shift(1).rolling(window=3).mean()
    return df_feat.dropna()

In [26]:
# 1. Train Model A - Frequency
train_freq = create_lag_features(final_df, 'Frequency')
X_freq = train_freq[['lag_1', 'lag_2', 'lag_3', 'rolling_mean_3']]
y_freq = train_freq['Frequency']

In [27]:
modelA_freq = GradientBoostingRegressor(n_estimators=100, learning_rate=0.05, max_depth=3, random_state=42)
modelA_freq.fit(X_freq, y_freq)

GradientBoostingRegressor(learning_rate=0.05, random_state=42)

In [28]:
# 2. Train Model A - Severity
train_sev = create_lag_features(final_df, 'Severity')
X_sev = train_sev[['lag_1', 'lag_2', 'lag_3', 'rolling_mean_3']]
y_sev = train_sev['Severity']

In [29]:
modelA_sev = GradientBoostingRegressor(n_estimators=100, learning_rate=0.05, max_depth=3, random_state=42)
modelA_sev.fit(X_sev, y_sev)

GradientBoostingRegressor(learning_rate=0.05, random_state=42)

In [30]:
# --- STEP 3: RECURSIVE FORECASTING (Aug - Dec 2025) ---
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=final_df['Period'].max() + 1, end=target_end, freq='M')

In [31]:
# History DataFrame (starts with actual data, grows with predictions)
history_df = final_df.copy()
current_exposure = history_df['Exposure'].iloc[-1] # Assuming constant exposure for forecast

predictions = []

In [32]:
for month in forecast_range:
    # 1. Build Features from History (Last 3 rows)
    last_3 = history_df.tail(3)
    
    # Feature Vector for Frequency
    freq_feats = np.array([[
        last_3['Frequency'].iloc[-1], # lag_1
        last_3['Frequency'].iloc[-2], # lag_2
        last_3['Frequency'].iloc[-3], # lag_3
        last_3['Frequency'].mean()    # rolling_mean_3
    ]])
    
    # Feature Vector for Severity
    sev_feats = np.array([[
        last_3['Severity'].iloc[-1],
        last_3['Severity'].iloc[-2],
        last_3['Severity'].iloc[-3],
        last_3['Severity'].mean()
    ]])
    
    # 2. Predict
    pred_frequency = modelA_freq.predict(freq_feats)[0]
    pred_sev = modelA_sev.predict(sev_feats)[0]
    
    # Safety: Ensure no negative predictions
    pred_frequency = max(0, pred_frequency)
    pred_sev = max(0, pred_sev)
    
    # 3. Calculate Derived Metrics
    pred_claim_count = pred_frequency
    pred_total_claim = pred_claim_count * pred_sev
    
    # 4. Append to History
    new_row = pd.DataFrame([{
        'Month_Period': month,
        'Claim_Count': pred_claim_count,
        'Total_Nominal': pred_total_claim,
        'Exposure': current_exposure,
        'Frequency': pred_frequency,
        'Severity': pred_sev
    }])
    history_df = pd.concat([history_df, new_row], ignore_index=True)
    
    # 5. Store if in Target Range (Aug - Dec)
    if month >= target_start:
        predictions.append({
            'Month': str(month),
            'Jumlah Klaim': int(round(pred_claim_count)),
            'Total Klaim': pred_total_claim,
            'Frequency': pred_frequency,
            'Severity': pred_sev
        })

c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

In [33]:
# --- STEP 4: FINAL RESULT ---
modelA_result_df = pd.DataFrame(predictions)

# Formatting for Display
pd.options.display.float_format = '{:f}'.format
print("Model A Prediction Results (Aug - Dec 2025):")
print(modelA_result_df)

Model A Prediction Results (Aug - Dec 2025):
     Month  Jumlah Klaim        Total Klaim  Frequency        Severity
0  2025-08           224 13006524431.265368 224.166173 58021798.163976
1  2025-09           252 12724009375.474773 252.393986 50413282.761677
2  2025-10           228 12129944638.245440 228.127103 53171869.905693
3  2025-11           209 11091678351.623657 208.801263 53120743.572480
4  2025-12           272 15872474142.575233 272.252172 58300633.602397

In [34]:
# Create a list to store the formatted rows
formatted_data = []

for index, row in modelA_result_df.iterrows():
    # Format the month from '2025-08' to '2025_08'
    month_str = str(row['Month']).replace('-', '_')
    
    # Append Frequency
    formatted_data.append({
        'id': f"{month_str}_Claim_Frequency",
        'value': row['Frequency']
    })
    
    # Append Severity
    formatted_data.append({
        'id': f"{month_str}_Claim_Severity",
        'value': row['Severity']
    })
    
    # Append Total Claim
    formatted_data.append({
        'id': f"{month_str}_Total_Claim",
        'value': row['Total Klaim']
    })

# Create the final dataframe
submission_df = pd.DataFrame(formatted_data)

# Display
print(submission_df)

# Export to CSV without the index number
submission_df.to_csv('submission_gb.csv', index=False)

print("File 'submission_gb.csv' saved successfully.")

                         id              value
0   2025_08_Claim_Frequency         224.166173
1    2025_08_Claim_Severity    58021798.163976
2       2025_08_Total_Claim 13006524431.265368
3   2025_09_Claim_Frequency         252.393986
4    2025_09_Claim_Severity    50413282.761677
5       2025_09_Total_Claim 12724009375.474773
6   2025_10_Claim_Frequency         228.127103
7    2025_10_Claim_Severity    53171869.905693
8       2025_10_Total_Claim 12129944638.245440
9   2025_11_Claim_Frequency         208.801263
10   2025_11_Claim_Severity    53120743.572480
11      2025_11_Total_Claim 11091678351.623657
12  2025_12_Claim_Frequency         272.252172
13   2025_12_Claim_Severity    58300633.602397
14      2025_12_Total_Claim 15872474142.575233
File 'submission_gb.csv' saved successfully.

RandomForest

In [35]:
from sklearn.ensemble import RandomForestRegressor

In [36]:
# --- 1. PREPARE DATA ---
# Ensure strict ordering
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

In [37]:
# Create Lag Features (Shift the data to use past values to predict future)
for col in ['Freq_Rate', 'Severity']:
    df[f'{col}_Lag1'] = df[col].shift(1)
    df[f'{col}_Lag2'] = df[col].shift(2)
    df[f'{col}_Lag3'] = df[col].shift(3)
    df[f'{col}_Mean3'] = df[col].rolling(window=3).mean()

In [38]:
# Drop NaN values created by shifting (first 3 rows)
train_df = df.dropna().copy()

# Define Features and Targets
features = ['Month', 'Freq_Rate_Lag1', 'Freq_Rate_Lag2', 'Freq_Rate_Lag3', 'Freq_Rate_Mean3', 
            'Severity_Lag1', 'Severity_Lag2', 'Severity_Lag3', 'Severity_Mean3']

In [39]:
# Model 1: Frequency (Count)
X = train_df[features]
y_freq = train_df['Frequency'] # Target is now the Count
model_freq = RandomForestRegressor(n_estimators=100, random_state=42)
model_freq.fit(X, y_freq)

RandomForestRegressor(random_state=42)

In [40]:
# Model 2: Severity
y_sev = train_df['Severity']
model_sev = RandomForestRegressor(n_estimators=100, random_state=42)
model_sev.fit(X, y_sev)

RandomForestRegressor(random_state=42)

In [41]:
# --- 2. FORECASTING LOOP ---

# Setup Forecast Dates
last_date_in_data = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')

# Generate range from next month after data ends -> until Dec 2025
forecast_range = pd.period_range(start=last_date_in_data + 1, end=target_end, freq='M')

# Initialize current_history with original data
current_history = df.copy()
predictions = []

print(f"Starting forecast from {forecast_range[0]} to {forecast_range[-1]}...")

for period in forecast_range:
    # 1. Extract Features from the most recent 'current_history'
    last_3 = current_history.tail(3)
    
    # Build feature vector matching the training features
    input_features = np.array([[
        period.month,                            # Month (Seasonality)
        last_3['Frequency'].iloc[-1],            # Lag 1 (Count)
        last_3['Frequency'].iloc[-2],            # Lag 2 (Count)
        last_3['Frequency'].iloc[-3],            # Lag 3 (Count)
        last_3['Frequency'].mean(),              # Rolling Mean (Count)
        last_3['Severity'].iloc[-1],             # Lag 1 Sev
        last_3['Severity'].iloc[-2],             # Lag 2 Sev
        last_3['Severity'].iloc[-3],             # Lag 3 Sev
        last_3['Severity'].mean()                # Rolling Mean Sev
    ]])
    
    # 2. Predict
    pred_frequency_count = model_freq.predict(input_features)[0] # Output is Count
    pred_severity = model_sev.predict(input_features)[0]
    
    # Safety: Ensure no negative predictions
    pred_frequency_count = max(0, pred_frequency_count)
    pred_severity = max(0, pred_severity)

    # 3. Calculate Total Claim
    # Total Claim = Count * Average Cost per Claim
    pred_total_claim = pred_frequency_count * pred_severity
    
    # 4. Save Prediction if inside our target window (Aug-Dec)
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_frequency_count,
            'Severity': pred_severity,
            'Total_Claim': pred_total_claim
        })
    
    # 5. Append prediction to history so next month uses it as "past data"
    new_row = pd.DataFrame([{
        'Year': period.year,
        'Month': period.month,
        'Frequency': pred_frequency_count, # Store predicted count
        'Severity': pred_severity,
        # Fill other cols like Exposure with 0 or NaN as they aren't used in features anymore
    }])
    
    current_history = pd.concat([current_history, new_row], ignore_index=True)

# Convert results to DataFrame
results_df = pd.DataFrame(predictions)
print("\nForecast Results (Aug - Dec 2025):")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])

Starting forecast from 2025-08 to 2025-12...

Forecast Results (Aug - Dec 2025):
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 243.170000 52361274.850084 12732691205.294868
1      2025-09 246.990000 51332984.216623 12678733771.663691
2      2025-10 245.720000 52089151.725578 12799346362.009136
3      2025-11 245.640000 52191767.647221 12820385804.863464
4      2025-12 243.930000 52127275.780670 12715406381.178873

c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [42]:
# --- 3. FORMAT FOR SUBMISSION ---
formatted_data = []

for index, row in results_df.iterrows():
    month_id = row['id_month']
    
    # 1. Frequency (Count)
    formatted_data.append({
        'id': f"{month_id}_Claim_Frequency",
        'value': row['Frequency']
    })
    
    # 2. Severity
    formatted_data.append({
        'id': f"{month_id}_Claim_Severity",
        'value': row['Severity']
    })
    
    # 3. Total Claim
    formatted_data.append({
        'id': f"{month_id}_Total_Claim",
        'value': row['Total_Claim']
    })

submission_df = pd.DataFrame(formatted_data)

# Export
submission_df.to_csv('submission_rf.csv', index=False)
print("\nSaved to 'submission_rf.csv'")

Saved to 'submission_rf.csv'

XGBoost

In [43]:
from xgboost import XGBRegressor

In [44]:
# --- 1. SETUP & PREPROCESSING ---
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

# A. Create Cyclical Month Features (Crucial for Seasonality)
# This helps the model understand that Month 12 is close to Month 1
df['month_sin'] = np.sin(2 * np.pi * df['Month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['Month']/12)

In [45]:
# B. Create Lag & Rolling Features
# We do this for both targets: Frequency (Count) and Severity
targets = ['Frequency', 'Severity']

for col in targets:
    df[f'{col}_Lag1'] = df[col].shift(1)
    df[f'{col}_Lag2'] = df[col].shift(2)
    df[f'{col}_Lag3'] = df[col].shift(3)
    df[f'{col}_RollMean3'] = df[col].rolling(window=3).mean()

In [46]:
# Drop the first 3 rows which now have NaNs
train_df = df.dropna().copy()

# --- 2. DEFINE FEATURES & LOG-TRANSFORM TARGETS ---
features = ['month_sin', 'month_cos', 
            'Frequency_Lag1', 'Frequency_Lag2', 'Frequency_Lag3', 'Frequency_RollMean3',
            'Severity_Lag1', 'Severity_Lag2', 'Severity_Lag3', 'Severity_RollMean3']

# Apply Log-Transformation to targets to handle skewness and prevent negative predictions
# log1p = log(x + 1) to handle zeros safely
y_freq_log = np.log1p(train_df['Frequency'])
y_sev_log = np.log1p(train_df['Severity'])

X = train_df[features]

In [47]:
# --- 3. TRAIN XGBOOST MODELS ---
# Using robust parameters to prevent overfitting
params = {
    'n_estimators': 500,
    'learning_rate': 0.05,
    'max_depth': 5,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'objective': 'reg:squarederror',
    'n_jobs': -1,
    'random_state': 42
}

print("Training Frequency Model...")
model_freq = XGBRegressor(**params)
model_freq.fit(X, y_freq_log)

print("Training Severity Model...")
model_sev = XGBRegressor(**params)
model_sev.fit(X, y_sev_log)

print("Training Complete.")

Training Frequency Model...
Training Severity Model...
Training Complete.

In [48]:
# --- 4. RECURSIVE FORECASTING (Aug - Dec 2025) ---

# Setup Dates
last_date = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

# Initialize History
current_history = df.copy()
predictions = []

print(f"\nForecasting from {forecast_range[0]} to {forecast_range[-1]}...")

for period in forecast_range:
    # A. Prepare Input Features from History
    last_3 = current_history.tail(3)
    
    # Calculate Cyclic Month for the forecast period
    p_month = period.month
    feat_sin = np.sin(2 * np.pi * p_month/12)
    feat_cos = np.cos(2 * np.pi * p_month/12)
    
    input_row = np.array([[
        feat_sin,
        feat_cos,
        last_3['Frequency'].iloc[-1],      # Lag1
        last_3['Frequency'].iloc[-2],      # Lag2
        last_3['Frequency'].iloc[-3],      # Lag3
        last_3['Frequency'].mean(),        # Mean3
        last_3['Severity'].iloc[-1],       # Lag1 Sev
        last_3['Severity'].iloc[-2],       # Lag2 Sev
        last_3['Severity'].iloc[-3],       # Lag3 Sev
        last_3['Severity'].mean()          # Mean3 Sev
    ]])
    
    # B. Predict (Result is in Log Scale)
    pred_freq_log = model_freq.predict(input_row)[0]
    pred_sev_log = model_sev.predict(input_row)[0]
    
    # C. Inverse Transform (Convert back from Log to Real numbers)
    pred_freq = np.expm1(pred_freq_log)
    pred_sev = np.expm1(pred_sev_log)
    
    # D. Calculate Total Claim
    pred_total_claim = pred_freq * pred_sev
    
    # E. Store & Update History
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_freq,
            'Severity': pred_sev,
            'Total_Claim': pred_total_claim
        })
        
    # Add new row to history for next iteration
    new_row = pd.DataFrame([{
        'Year': period.year,
        'Month': period.month,
        'Frequency': pred_freq,
        'Severity': pred_sev,
        # Recalculate cyclic features for the history df if needed, though only raw cols are used for lags
        'month_sin': feat_sin,
        'month_cos': feat_cos
    }])
    
    current_history = pd.concat([current_history, new_row], ignore_index=True)

results_df = pd.DataFrame(predictions)

# Show Quick Preview
print("\nForecast Results:")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])

Forecasting from 2025-08 to 2025-12...

Forecast Results:
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 260.144257 53604112.000000 13944802304.000000
1      2025-09 250.288895 52227120.000000 13071867904.000000
2      2025-10 256.413696 50671360.000000 12992830464.000000
3      2025-11 255.200531 50869876.000000 12982019072.000000
4      2025-12 234.500229 53290840.000000 12496713728.000000

In [49]:
# --- 5. FORMAT AND EXPORT ---
formatted_data = []

for index, row in results_df.iterrows():
    m_id = row['id_month']
    
    # Frequency
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    # Severity
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    # Total Claim
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

submission_df = pd.DataFrame(formatted_data)
submission_df.to_csv('submission_xgboost.csv', index=False)

print("\nSuccessfully saved to 'submission_xgboost.csv'")

Successfully saved to 'submission_xgboost.csv'

LightGBM

In [50]:
import lightgbm as lgb
import optuna
from sklearn.metrics import mean_absolute_percentage_error

c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [51]:
# --- 1. SETUP & PREPROCESSING ---
# Ensure strict ordering
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

# A. Create Cyclical Month Features (Seasonality)
# Transforms month 1-12 into coordinates on a circle so Dec (12) is close to Jan (1)
df['month_sin'] = np.sin(2 * np.pi * df['Month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['Month']/12)

In [52]:
# B. Create Lag & Rolling Features
targets = ['Frequency', 'Severity']

for col in targets:
    # Immediate past values
    df[f'{col}_Lag1'] = df[col].shift(1)
    df[f'{col}_Lag2'] = df[col].shift(2)
    df[f'{col}_Lag3'] = df[col].shift(3)
    # Trend over the last window
    df[f'{col}_RollMean3'] = df[col].rolling(window=3).mean()

# Drop rows with NaN (created by lags) for training
train_df = df.dropna().copy()

In [53]:
# --- 2. DEFINE FEATURES & LOG-TRANSFORM TARGETS ---
features = ['month_sin', 'month_cos', 
            'Frequency_Lag1', 'Frequency_Lag2', 'Frequency_Lag3', 'Frequency_RollMean3',
            'Severity_Lag1', 'Severity_Lag2', 'Severity_Lag3', 'Severity_RollMean3']

# Log-Transform Targets: Handles skewness & prevents negative predictions
y_freq_log = np.log1p(train_df['Frequency'])
y_sev_log = np.log1p(train_df['Severity'])

X = train_df[features]

In [54]:
# --- 3. TRAIN LIGHTGBM MODELS ---
# Parameters optimized for small tabular data to prevent overfitting
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'n_estimators': 500,       # Number of trees
    'learning_rate': 0.05,     # Step size (smaller is safer)
    'num_leaves': 31,          # Max leaves per tree
    'max_depth': -1,           # No limit (let num_leaves control complexity)
    'min_child_samples': 5,    # Important for small data: min data in a leaf
    'subsample': 0.8,          # Use 80% of rows per iteration
    'colsample_bytree': 0.8,   # Use 80% of features per iteration
    'random_state': 42,
    'verbose': -1              # Silence warnings
}

In [55]:
print("Training Frequency (Count) Model...")
model_freq = lgb.LGBMRegressor(**params)
model_freq.fit(X, y_freq_log)

Training Frequency (Count) Model...

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.05, metric='rmse',
              min_child_samples=5, n_estimators=500, objective='regression',
              random_state=42, subsample=0.8, verbose=-1)

In [56]:
print("Training Severity Model...")
model_sev = lgb.LGBMRegressor(**params)
model_sev.fit(X, y_sev_log)

Training Severity Model...

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.05, metric='rmse',
              min_child_samples=5, n_estimators=500, objective='regression',
              random_state=42, subsample=0.8, verbose=-1)

In [57]:
# --- 4. RECURSIVE FORECASTING (Aug - Dec 2025) ---

# Define Time Range
last_date = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

# Initialize History with original data
current_history = df.copy()
predictions = []

print(f"\nForecasting from {forecast_range[0]} to {forecast_range[-1]}...")

for period in forecast_range:
    # A. Build Input Row from History (Last 3 months)
    last_3 = current_history.tail(3)
    
    # Calculate Cyclic Month for the FORECAST month
    p_month = period.month
    feat_sin = np.sin(2 * np.pi * p_month/12)
    feat_cos = np.cos(2 * np.pi * p_month/12)
    
    # Construct Feature Array (must match training order)
    input_row = np.array([[
        feat_sin,
        feat_cos,
        last_3['Frequency'].iloc[-1],      # Lag1
        last_3['Frequency'].iloc[-2],      # Lag2
        last_3['Frequency'].iloc[-3],      # Lag3
        last_3['Frequency'].mean(),        # RollMean3
        last_3['Severity'].iloc[-1],       # Lag1 Sev
        last_3['Severity'].iloc[-2],       # Lag2 Sev
        last_3['Severity'].iloc[-3],       # Lag3 Sev
        last_3['Severity'].mean()          # RollMean3 Sev
    ]])
    
    # B. Predict (Log Scale)
    pred_freq_log = model_freq.predict(input_row)[0]
    pred_sev_log = model_sev.predict(input_row)[0]
    
    # C. Inverse Transform (Back to Real Scale)
    pred_freq = np.expm1(pred_freq_log)
    pred_sev = np.expm1(pred_sev_log)
    
    # D. Calculate Total Claim (Count * Severity)
    pred_total_claim = pred_freq * pred_sev
    
    # E. Store Prediction (Only if in Aug-Dec window)
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_freq,
            'Severity': pred_sev,
            'Total_Claim': pred_total_claim
        })
        
    # F. Update History for Next Iteration
    new_row = pd.DataFrame([{
        'Year': period.year,
        'Month': period.month,
        'Frequency': pred_freq,
        'Severity': pred_sev,
        # Helper cols (not strictly needed as we rebuild them, but good for consistency)
        'month_sin': feat_sin,
        'month_cos': feat_cos
    }])
    
    current_history = pd.concat([current_history, new_row], ignore_index=True)

# Create Results DataFrame
results_df = pd.DataFrame(predictions)

# Show Preview
print("\nForecast Results:")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])

Forecasting from 2025-08 to 2025-12...

Forecast Results:
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 233.816257 52797448.293320 12344901728.604944
1      2025-09 247.148268 48833481.821214 12069110457.186052
2      2025-10 232.643995 54516762.430975 12682997398.343206
3      2025-11 220.987987 48841204.159681 10793319398.009361
4      2025-12 237.003254 60426164.856133 14321197670.333136

c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [58]:
# --- 5. FORMAT AND EXPORT ---
formatted_data = []

for index, row in results_df.iterrows():
    m_id = row['id_month']
    
    # Frequency
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    # Severity
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    # Total Claim
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

submission_df = pd.DataFrame(formatted_data)
submission_df.to_csv('submission_lightgbm.csv', index=False)

print("\nSuccessfully saved to 'submission_lightgbm.csv'")

Successfully saved to 'submission_lightgbm.csv'

Improved Light GBM

In [59]:
# --- 1. ENHANCED FEATURE ENGINEERING ---
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

# A. Cyclical Month
df['month_sin'] = np.sin(2 * np.pi * df['Month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['Month']/12)

# B. Expanded Lags & Rolling Windows
targets = ['Frequency', 'Severity']

for col in targets:
    # Lags
    df[f'{col}_Lag1'] = df[col].shift(1)
    df[f'{col}_Lag2'] = df[col].shift(2)
    df[f'{col}_Lag3'] = df[col].shift(3)
    
    # Rolling Means (Short vs Long term trend)
    df[f'{col}_Mean3'] = df[col].rolling(window=3).mean()
    df[f'{col}_Mean6'] = df[col].rolling(window=6).mean() # New: Half-year trend
    
    # Rolling Volatility (Standard Deviation)
    df[f'{col}_Std3'] = df[col].rolling(window=3).std()   # New: Is data becoming unstable?

# Drop NaNs
train_df = df.dropna().copy()

features = [c for c in train_df.columns if 'Lag' in c or 'Mean' in c or 'Std' in c or 'month_' in c]
X = train_df[features]

# We train on Log Scale to handle skew, but optimize for MAPE
y_freq = train_df['Frequency']
y_sev = train_df['Severity']

# --- 2. OPTUNA OPTIMIZATION FUNCTION ---

def optimize_lightgbm(target_col, n_trials=50):
    print(f"\n--- Optimizing {target_col} ---")
    y = train_df[target_col]
    
    # Time-Series Split for Validation (Train on first 80%, Validate on last 20%)
    split_idx = int(len(X) * 0.8)
    X_train, X_val = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_val = y.iloc[:split_idx], y.iloc[split_idx:]
    
    def objective(trial):
        params = {
            'objective': 'mape', # Directly optimize MAPE!
            'metric': 'mape',
            'verbosity': -1,
            'boosting_type': 'gbdt',
            'random_state': 42,
            'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
            'num_leaves': trial.suggest_int('num_leaves', 20, 100),
            'max_depth': trial.suggest_int('max_depth', 3, 12),
            'min_child_samples': trial.suggest_int('min_child_samples', 2, 20),
            'subsample': trial.suggest_float('subsample', 0.5, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        }
        
        model = lgb.LGBMRegressor(**params)
        model.fit(X_train, y_train)
        preds = model.predict(X_val)
        
        # Calculate MAPE
        mape = mean_absolute_percentage_error(y_val, preds)
        return mape

    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=n_trials)
    
    print(f"Best MAPE for {target_col}: {study.best_value:.4f}")
    return study.best_params

# --- 3. RUN OPTIMIZATION ---
# Run 50 trials for each model to find the perfect parameters
best_params_freq = optimize_lightgbm('Frequency', n_trials=50)
best_params_sev = optimize_lightgbm('Severity', n_trials=50)

# --- 4. TRAIN FINAL MODELS WITH BEST PARAMS ---
print("\nTraining Final Models...")
final_model_freq = lgb.LGBMRegressor(**best_params_freq)
final_model_freq.fit(X, y_freq)

final_model_sev = lgb.LGBMRegressor(**best_params_sev)
final_model_sev.fit(X, y_sev)

[I 2026-02-22 20:15:01,038] A new study created in memory with name: no-name-5034c6e1-cd6b-41ab-b7ba-ccd383ee35b7
[I 2026-02-22 20:15:01,054] Trial 0 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 709, 'learning_rate': 0.01908107988602684, 'num_leaves': 84, 'max_depth': 10, 'min_child_samples': 16, 'subsample': 0.8515922968667107, 'colsample_bytree': 0.9566001592947428, 'reg_alpha': 0.10667583639736908, 'reg_lambda': 6.1424303167034584e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,070] Trial 1 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 482, 'learning_rate': 0.016560148313955775, 'num_leaves': 39, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.7409583120949748, 'colsample_bytree': 0.6550163210489961, 'reg_alpha': 0.5408029503050257, 'reg_lambda': 0.0010427935054212291}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,079] Trial 2 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 463, 'learning_rate': 0.01698511628419723, 'num_leaves': 21, 'max_depth': 9, 'min_child_samples': 18, 'subsample': 0.8131795992852455, 'colsample_bytree': 0.9830613533074369, 'reg_alpha': 6.935350609189882e-07, 'reg_lambda': 1.6472328322067268e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,087] Trial 3 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 461, 'learning_rate': 0.08266174313800796, 'num_leaves': 22, 'max_depth': 4, 'min_child_samples': 16, 'subsample': 0.5227611750183597, 'colsample_bytree': 0.7791373132256654, 'reg_alpha': 0.15176908247031437, 'reg_lambda': 3.196741161888949e-05}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,098] Trial 4 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 609, 'learning_rate': 0.05832562383222562, 'num_leaves': 31, 'max_depth': 10, 'min_child_samples': 11, 'subsample': 0.6746938104947826, 'colsample_bytree': 0.5380608128750569, 'reg_alpha': 6.27348509677295e-06, 'reg_lambda': 5.707065115463377e-07}. Best is trial 0 with value: 0.06117959988252875.

--- Optimizing Frequency ---

[I 2026-02-22 20:15:01,107] Trial 5 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 278, 'learning_rate': 0.020139711961973675, 'num_leaves': 33, 'max_depth': 9, 'min_child_samples': 15, 'subsample': 0.7783714455106039, 'colsample_bytree': 0.5138858458859059, 'reg_alpha': 2.1842662470882914e-06, 'reg_lambda': 1.4473998430297468}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,116] Trial 6 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 626, 'learning_rate': 0.020267228323628577, 'num_leaves': 78, 'max_depth': 12, 'min_child_samples': 13, 'subsample': 0.5857809923973682, 'colsample_bytree': 0.6907954424916825, 'reg_alpha': 0.0008555045140102968, 'reg_lambda': 2.2231834510581387e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,126] Trial 7 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 327, 'learning_rate': 0.0575359840929628, 'num_leaves': 62, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.5720053836630516, 'colsample_bytree': 0.8712493454991473, 'reg_alpha': 0.007326710399379485, 'reg_lambda': 0.002934335386377292}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,134] Trial 8 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 214, 'learning_rate': 0.007556199137879104, 'num_leaves': 91, 'max_depth': 4, 'min_child_samples': 8, 'subsample': 0.9414034630918644, 'colsample_bytree': 0.6768832982099888, 'reg_alpha': 0.00040333360416534354, 'reg_lambda': 0.0001145365272576506}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,141] Trial 9 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 250, 'learning_rate': 0.007868769381049958, 'num_leaves': 52, 'max_depth': 10, 'min_child_samples': 15, 'subsample': 0.9726037652153785, 'colsample_bytree': 0.7267517732780393, 'reg_alpha': 1.2957871586350299e-08, 'reg_lambda': 0.01146226140436669}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,173] Trial 10 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 908, 'learning_rate': 0.03688219964165096, 'num_leaves': 96, 'max_depth': 6, 'min_child_samples': 2, 'subsample': 0.8723535961461136, 'colsample_bytree': 0.9958661554393555, 'reg_alpha': 4.465563708125053, 'reg_lambda': 5.07262868707742e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,195] Trial 11 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 793, 'learning_rate': 0.012081380457007265, 'num_leaves': 52, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7227407931428161, 'colsample_bytree': 0.8537180361162047, 'reg_alpha': 8.663907487462927, 'reg_lambda': 0.009324552426385479}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,219] Trial 12 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 727, 'learning_rate': 0.03167685240686437, 'num_leaves': 71, 'max_depth': 12, 'min_child_samples': 9, 'subsample': 0.8694594321873379, 'colsample_bytree': 0.592473286142438, 'reg_alpha': 0.05990337802004763, 'reg_lambda': 1.3970713929617605e-08}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,256] Trial 13 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 999, 'learning_rate': 0.011662109079232465, 'num_leaves': 42, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6738684979117141, 'colsample_bytree': 0.6148581507322393, 'reg_alpha': 0.13568058778972072, 'reg_lambda': 0.790909310328471}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,278] Trial 14 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 460, 'learning_rate': 0.005434851861210207, 'num_leaves': 85, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.858774413104394, 'colsample_bytree': 0.8229117320032615, 'reg_alpha': 0.9848695568316971, 'reg_lambda': 0.0007917938177593598}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,303] Trial 15 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 124, 'learning_rate': 0.03282349420972853, 'num_leaves': 67, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.7540794883675962, 'colsample_bytree': 0.9124253081755086, 'reg_alpha': 0.007008031026492425, 'reg_lambda': 0.09725858090654906}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,350] Trial 16 finished with value: 0.0807926170356579 and parameters: {'n_estimators': 746, 'learning_rate': 0.012933367661234776, 'num_leaves': 50, 'max_depth': 11, 'min_child_samples': 4, 'subsample': 0.6867366062981881, 'colsample_bytree': 0.6340968141230765, 'reg_alpha': 0.009995755831980629, 'reg_lambda': 7.582413653178623e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,377] Trial 17 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 613, 'learning_rate': 0.02598373263348491, 'num_leaves': 100, 'max_depth': 3, 'min_child_samples': 13, 'subsample': 0.9246461518536608, 'colsample_bytree': 0.7650799648566879, 'reg_alpha': 0.53640337980294, 'reg_lambda': 0.00010366540755341994}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,400] Trial 18 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 372, 'learning_rate': 0.014562398384853799, 'num_leaves': 79, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.8124044191768984, 'colsample_bytree': 0.9303942769301545, 'reg_alpha': 4.1198066729882024e-05, 'reg_lambda': 5.4329287040026445e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,428] Trial 19 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 825, 'learning_rate': 0.042384959954523814, 'num_leaves': 41, 'max_depth': 10, 'min_child_samples': 10, 'subsample': 0.633959706648227, 'colsample_bytree': 0.5684285199016186, 'reg_alpha': 0.03334084287719918, 'reg_lambda': 0.12384209769545401}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,454] Trial 20 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 564, 'learning_rate': 0.009333081953557833, 'num_leaves': 57, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.7817519095099662, 'colsample_bytree': 0.6633110094881611, 'reg_alpha': 0.9900153984454969, 'reg_lambda': 0.0006019013140268913}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,480] Trial 21 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 490, 'learning_rate': 0.01797765808595461, 'num_leaves': 24, 'max_depth': 9, 'min_child_samples': 20, 'subsample': 0.8337203342842485, 'colsample_bytree': 0.9955136911154179, 'reg_alpha': 6.348394506761892e-08, 'reg_lambda': 1.0640550466306036e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,506] Trial 22 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 425, 'learning_rate': 0.02539810892763311, 'num_leaves': 33, 'max_depth': 9, 'min_child_samples': 18, 'subsample': 0.9078839095610894, 'colsample_bytree': 0.94639448127132, 'reg_alpha': 3.805659695296592e-05, 'reg_lambda': 1.3687127011832893e-08}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,535] Trial 23 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 658, 'learning_rate': 0.016930251666437173, 'num_leaves': 20, 'max_depth': 11, 'min_child_samples': 18, 'subsample': 0.7982044931354463, 'colsample_bytree': 0.9636983224916232, 'reg_alpha': 4.256651395073951e-07, 'reg_lambda': 1.217093302571337e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,560] Trial 24 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 534, 'learning_rate': 0.023835874254349625, 'num_leaves': 41, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.7402196887446595, 'colsample_bytree': 0.8767383135345251, 'reg_alpha': 0.0007977134598893665, 'reg_lambda': 6.770598166868421e-08}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,585] Trial 25 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 375, 'learning_rate': 0.016141352144154356, 'num_leaves': 28, 'max_depth': 9, 'min_child_samples': 14, 'subsample': 0.8380949567427303, 'colsample_bytree': 0.8070961851107294, 'reg_alpha': 9.555725504904969e-05, 'reg_lambda': 2.8785956346614293e-05}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,613] Trial 26 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 683, 'learning_rate': 0.010247223684095506, 'num_leaves': 41, 'max_depth': 11, 'min_child_samples': 19, 'subsample': 0.7139587236096557, 'colsample_bytree': 0.9000011095181895, 'reg_alpha': 3.6132256127759454e-07, 'reg_lambda': 7.429150980138201e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,644] Trial 27 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 541, 'learning_rate': 0.014579602604864699, 'num_leaves': 47, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.9979221257493205, 'colsample_bytree': 0.7169717363817579, 'reg_alpha': 2.75772497271173, 'reg_lambda': 2.8470996716649014e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,676] Trial 28 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 829, 'learning_rate': 0.005456908769773536, 'num_leaves': 73, 'max_depth': 10, 'min_child_samples': 8, 'subsample': 0.9026449476559404, 'colsample_bytree': 0.961132817090164, 'reg_alpha': 5.651521507663698e-06, 'reg_lambda': 2.7933479404639862e-05}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,712] Trial 29 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 513, 'learning_rate': 0.027428917464552508, 'num_leaves': 26, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.5127234548090556, 'colsample_bytree': 0.7756379462392677, 'reg_alpha': 0.26670126279713213, 'reg_lambda': 0.00019817969867659245}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,753] Trial 30 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 417, 'learning_rate': 0.04543696945885551, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.7648880724806805, 'colsample_bytree': 0.8018696871955091, 'reg_alpha': 0.0016445791292781769, 'reg_lambda': 1.830151313594844e-05}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,780] Trial 31 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 572, 'learning_rate': 0.08510030295221116, 'num_leaves': 34, 'max_depth': 3, 'min_child_samples': 16, 'subsample': 0.5079574778487759, 'colsample_bytree': 0.5523030782503199, 'reg_alpha': 0.03093414918912536, 'reg_lambda': 3.274355677896838e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,809] Trial 32 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 452, 'learning_rate': 0.020476959628403058, 'num_leaves': 21, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.621196956952424, 'colsample_bytree': 0.8361213805138337, 'reg_alpha': 0.14686759110395448, 'reg_lambda': 9.290443834391768}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,832] Trial 33 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 310, 'learning_rate': 0.07715694695341913, 'num_leaves': 30, 'max_depth': 4, 'min_child_samples': 11, 'subsample': 0.5555378100681165, 'colsample_bytree': 0.8979402092413328, 'reg_alpha': 1.2322134540836818, 'reg_lambda': 0.0019631474654786527}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,866] Trial 34 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 623, 'learning_rate': 0.055184876550624415, 'num_leaves': 36, 'max_depth': 9, 'min_child_samples': 17, 'subsample': 0.8040117300527476, 'colsample_bytree': 0.7274855334340515, 'reg_alpha': 0.0053986918841986775, 'reg_lambda': 1.596468983180115e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,898] Trial 35 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 380, 'learning_rate': 0.09726123689126893, 'num_leaves': 26, 'max_depth': 4, 'min_child_samples': 19, 'subsample': 0.6392025846042791, 'colsample_bytree': 0.6473320428216007, 'reg_alpha': 9.951864562367163e-07, 'reg_lambda': 4.4030703829241034e-05}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,928] Trial 36 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 492, 'learning_rate': 0.019871815727077285, 'num_leaves': 36, 'max_depth': 9, 'min_child_samples': 14, 'subsample': 0.5562475112891501, 'colsample_bytree': 0.5126920797856258, 'reg_alpha': 0.0602031382251942, 'reg_lambda': 1.5802955393327656e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,952] Trial 37 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 220, 'learning_rate': 0.021487871786014703, 'num_leaves': 87, 'max_depth': 10, 'min_child_samples': 10, 'subsample': 0.5977055058325939, 'colsample_bytree': 0.7007908828473834, 'reg_alpha': 0.00012724795549910257, 'reg_lambda': 0.006141897536348898}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:01,979] Trial 38 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 695, 'learning_rate': 0.0675689023426764, 'num_leaves': 20, 'max_depth': 10, 'min_child_samples': 14, 'subsample': 0.9605445818755642, 'colsample_bytree': 0.9768347461865096, 'reg_alpha': 1.123934995442615e-08, 'reg_lambda': 3.594139485278634e-08}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,004] Trial 39 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 332, 'learning_rate': 0.008239955386206536, 'num_leaves': 46, 'max_depth': 11, 'min_child_samples': 17, 'subsample': 0.8989196707440625, 'colsample_bytree': 0.8682882907428033, 'reg_alpha': 0.0016011031188366163, 'reg_lambda': 0.00010141816721028494}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,037] Trial 40 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 571, 'learning_rate': 0.029941819980151503, 'num_leaves': 56, 'max_depth': 12, 'min_child_samples': 19, 'subsample': 0.69171912264044, 'colsample_bytree': 0.9235466425330598, 'reg_alpha': 8.679959622061393, 'reg_lambda': 0.042578395978690294}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,071] Trial 41 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 600, 'learning_rate': 0.06459854217465746, 'num_leaves': 31, 'max_depth': 10, 'min_child_samples': 8, 'subsample': 0.7226846182505686, 'colsample_bytree': 0.5602817295635582, 'reg_alpha': 4.6453964274795455e-06, 'reg_lambda': 4.526465640880713e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,103] Trial 42 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 763, 'learning_rate': 0.0980077816493653, 'num_leaves': 24, 'max_depth': 11, 'min_child_samples': 9, 'subsample': 0.6570916364712336, 'colsample_bytree': 0.5336846445596085, 'reg_alpha': 4.868032724334925e-06, 'reg_lambda': 9.112091227156655e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,134] Trial 43 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 660, 'learning_rate': 0.047018688227294214, 'num_leaves': 38, 'max_depth': 9, 'min_child_samples': 12, 'subsample': 0.7734758924635752, 'colsample_bytree': 0.598023235823671, 'reg_alpha': 2.0004868999567199e-07, 'reg_lambda': 1.951797654135283e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,183] Trial 44 finished with value: 0.11645182120773517 and parameters: {'n_estimators': 461, 'learning_rate': 0.01421370985852014, 'num_leaves': 64, 'max_depth': 8, 'min_child_samples': 3, 'subsample': 0.8399597556964564, 'colsample_bytree': 0.6231173855943668, 'reg_alpha': 4.835712608616171e-08, 'reg_lambda': 3.347256280718246e-08}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,222] Trial 45 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 916, 'learning_rate': 0.03487428701381149, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.8648519451765354, 'colsample_bytree': 0.6749613903161211, 'reg_alpha': 1.571443621672795e-05, 'reg_lambda': 0.00035325198962081244}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,251] Trial 46 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 287, 'learning_rate': 0.053442672915930085, 'num_leaves': 24, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.8161639741850705, 'colsample_bytree': 0.7423020543003073, 'reg_alpha': 1.225004655193094e-06, 'reg_lambda': 0.0015157127215929128}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,285] Trial 47 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 411, 'learning_rate': 0.07978897105059435, 'num_leaves': 94, 'max_depth': 12, 'min_child_samples': 10, 'subsample': 0.5338707236647833, 'colsample_bytree': 0.6002258489228441, 'reg_alpha': 2.0967402202918186, 'reg_lambda': 5.182996563056931e-07}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,321] Trial 48 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 597, 'learning_rate': 0.010741430566213463, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.7483782896828618, 'colsample_bytree': 0.9986050494178603, 'reg_alpha': 0.021274762564282634, 'reg_lambda': 8.285037087982709e-06}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,352] Trial 49 finished with value: 0.06117959988252875 and parameters: {'n_estimators': 504, 'learning_rate': 0.018527337248823755, 'num_leaves': 72, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.594584496666382, 'colsample_bytree': 0.5007096774506047, 'reg_alpha': 0.12778982372627926, 'reg_lambda': 7.185629458345871e-05}. Best is trial 0 with value: 0.06117959988252875.
[I 2026-02-22 20:15:02,356] A new study created in memory with name: no-name-e66742a6-d0e7-4110-9828-3f56590c89c4
[I 2026-02-22 20:15:02,366] Trial 0 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 130, 'learning_rate': 0.0842085563039455, 'num_leaves': 49, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.772587623941132, 'colsample_bytree': 0.7870938530766903, 'reg_alpha': 5.244662614053785e-06, 'reg_lambda': 6.834926279053943e-05}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,376] Trial 1 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 372, 'learning_rate': 0.015786240564939664, 'num_leaves': 85, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.8305108220293953, 'colsample_bytree': 0.7354544225958718, 'reg_alpha': 0.028191050670055964, 'reg_lambda': 2.550187902112626e-08}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,391] Trial 2 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 531, 'learning_rate': 0.03943998323364301, 'num_leaves': 22, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.8501326534154103, 'colsample_bytree': 0.6129640419669988, 'reg_alpha': 5.702835221779563e-06, 'reg_lambda': 0.00033667192814755483}. Best is trial 0 with value: 0.04812267077268912.

Best MAPE for Frequency: 0.0612

--- Optimizing Severity ---

[I 2026-02-22 20:15:02,569] Trial 14 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 271, 'learning_rate': 0.06221614950055737, 'num_leaves': 77, 'max_depth': 6, 'min_child_samples': 3, 'subsample': 0.7175696216786838, 'colsample_bytree': 0.7531473740734466, 'reg_alpha': 0.03973702283496695, 'reg_lambda': 0.003439289703536379}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,589] Trial 15 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 460, 'learning_rate': 0.03464720884586533, 'num_leaves': 56, 'max_depth': 9, 'min_child_samples': 16, 'subsample': 0.5820235579648914, 'colsample_bytree': 0.6911308160300118, 'reg_alpha': 6.144183987768658e-07, 'reg_lambda': 3.6068678286209763e-06}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,614] Trial 16 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 752, 'learning_rate': 0.02132683008758179, 'num_leaves': 37, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.9848116729789502, 'colsample_bytree': 0.791727224048348, 'reg_alpha': 5.55210824645763e-05, 'reg_lambda': 0.09196633394235992}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,634] Trial 17 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 249, 'learning_rate': 0.012007070144219615, 'num_leaves': 57, 'max_depth': 3, 'min_child_samples': 18, 'subsample': 0.7961184721418606, 'colsample_bytree': 0.8904016639090946, 'reg_alpha': 0.01737593504991, 'reg_lambda': 0.00019279536055256602}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,656] Trial 18 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 501, 'learning_rate': 0.005871298422332447, 'num_leaves': 99, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.9166997110133767, 'colsample_bytree': 0.6666919842660239, 'reg_alpha': 0.30602826734123173, 'reg_lambda': 8.806616027346446e-07}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,678] Trial 19 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 294, 'learning_rate': 0.05126354953614778, 'num_leaves': 76, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.7168226828497737, 'colsample_bytree': 0.5937719289216361, 'reg_alpha': 0.000101243293162985, 'reg_lambda': 1.494065186099791e-08}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,702] Trial 20 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 652, 'learning_rate': 0.026693247221178884, 'num_leaves': 49, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.5981323537911759, 'colsample_bytree': 0.8875134547823766, 'reg_alpha': 0.00742619695660415, 'reg_lambda': 2.0253274016445992e-05}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,741] Trial 21 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 551, 'learning_rate': 0.03974301579225661, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.8352226773394834, 'colsample_bytree': 0.5870483333768862, 'reg_alpha': 1.0187126372346458e-05, 'reg_lambda': 0.00035311395173403236}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,769] Trial 22 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 428, 'learning_rate': 0.07133079740474622, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.8702124824667998, 'colsample_bytree': 0.7220474536203519, 'reg_alpha': 4.034545288707575e-07, 'reg_lambda': 0.000708688805430804}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,802] Trial 23 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 699, 'learning_rate': 0.04553455558167107, 'num_leaves': 35, 'max_depth': 4, 'min_child_samples': 2, 'subsample': 0.8091487142195649, 'colsample_bytree': 0.6346430205456572, 'reg_alpha': 8.343666107494187e-07, 'reg_lambda': 0.09848893024653532}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,826] Trial 24 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 187, 'learning_rate': 0.027745609108041816, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7428113839957863, 'colsample_bytree': 0.7931144946544045, 'reg_alpha': 2.5680580204846886e-05, 'reg_lambda': 0.00124198455824197}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,857] Trial 25 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 363, 'learning_rate': 0.06754780227831489, 'num_leaves': 43, 'max_depth': 9, 'min_child_samples': 4, 'subsample': 0.9535742770059668, 'colsample_bytree': 0.5823944594421208, 'reg_alpha': 2.262413826596548e-06, 'reg_lambda': 1.6877377169476567e-05}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,884] Trial 26 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 535, 'learning_rate': 0.016065544918033973, 'num_leaves': 60, 'max_depth': 4, 'min_child_samples': 17, 'subsample': 0.867030461891293, 'colsample_bytree': 0.9988539549997087, 'reg_alpha': 1.0898428290954198e-07, 'reg_lambda': 0.04538324939230327}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,914] Trial 27 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 465, 'learning_rate': 0.09892405402887842, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.7459934428173953, 'colsample_bytree': 0.6415316434215182, 'reg_alpha': 0.16799258037854026, 'reg_lambda': 9.60729055606948e-05}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,945] Trial 28 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 612, 'learning_rate': 0.028720271351229378, 'num_leaves': 72, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.834734616850659, 'colsample_bytree': 0.7092739262945932, 'reg_alpha': 2.376431712610795e-05, 'reg_lambda': 3.1021383472126317e-06}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:02,977] Trial 29 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 847, 'learning_rate': 0.008538754040237578, 'num_leaves': 88, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.8192017371828807, 'colsample_bytree': 0.7894936579434981, 'reg_alpha': 0.0007182425482565517, 'reg_lambda': 0.0288817708696022}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,002] Trial 30 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 203, 'learning_rate': 0.012669736016038045, 'num_leaves': 54, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.8838266191165898, 'colsample_bytree': 0.5576487410969527, 'reg_alpha': 0.00029930307084948866, 'reg_lambda': 0.41080135824641995}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,033] Trial 31 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 793, 'learning_rate': 0.009675761249436709, 'num_leaves': 83, 'max_depth': 10, 'min_child_samples': 13, 'subsample': 0.7809968670159482, 'colsample_bytree': 0.9326102196253447, 'reg_alpha': 0.0032729033610783254, 'reg_lambda': 0.0066687124395426595}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,064] Trial 32 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 988, 'learning_rate': 0.007140850843409436, 'num_leaves': 86, 'max_depth': 12, 'min_child_samples': 9, 'subsample': 0.8301390639436466, 'colsample_bytree': 0.5330708762673005, 'reg_alpha': 0.0012633699817671783, 'reg_lambda': 0.0024389050208325556}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,091] Trial 33 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 722, 'learning_rate': 0.020458743650477704, 'num_leaves': 90, 'max_depth': 11, 'min_child_samples': 15, 'subsample': 0.9410066618671007, 'colsample_bytree': 0.9055423429095553, 'reg_alpha': 8.957903014322391e-05, 'reg_lambda': 5.416092095743275e-05}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,114] Trial 34 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 112, 'learning_rate': 0.010983243207846188, 'num_leaves': 64, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.8505589431478073, 'colsample_bytree': 0.9985788037869858, 'reg_alpha': 1.5124661628699076e-07, 'reg_lambda': 0.7639769443121656}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,145] Trial 35 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 418, 'learning_rate': 0.016088093496370356, 'num_leaves': 99, 'max_depth': 10, 'min_child_samples': 12, 'subsample': 0.7921857442096925, 'colsample_bytree': 0.8415781180775828, 'reg_alpha': 0.8922686017785458, 'reg_lambda': 0.010690438165658733}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,184] Trial 36 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 588, 'learning_rate': 0.01916833344519636, 'num_leaves': 74, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.7620671500548026, 'colsample_bytree': 0.5075520857361461, 'reg_alpha': 2.142951974636658e-06, 'reg_lambda': 1.3087249596614447e-07}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,214] Trial 37 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 905, 'learning_rate': 0.00717045468125811, 'num_leaves': 82, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.7171800137511631, 'colsample_bytree': 0.9458288678223645, 'reg_alpha': 1.6680262510147326e-08, 'reg_lambda': 0.0006799398799357284}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,237] Trial 38 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 313, 'learning_rate': 0.013314942992072263, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.8931759620967274, 'colsample_bytree': 0.769154321540918, 'reg_alpha': 0.0013903102540619293, 'reg_lambda': 7.572326983903075e-07}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,267] Trial 39 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 663, 'learning_rate': 0.07834002646886704, 'num_leaves': 44, 'max_depth': 4, 'min_child_samples': 7, 'subsample': 0.9223782027867917, 'colsample_bytree': 0.6122425233202136, 'reg_alpha': 0.00016793389316698245, 'reg_lambda': 5.992071081843177e-06}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,291] Trial 40 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 499, 'learning_rate': 0.01835470450284135, 'num_leaves': 94, 'max_depth': 10, 'min_child_samples': 18, 'subsample': 0.8504937864519613, 'colsample_bytree': 0.9704370851124037, 'reg_alpha': 0.013774593221279122, 'reg_lambda': 6.043076892445595e-08}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,315] Trial 41 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 154, 'learning_rate': 0.02405973336727498, 'num_leaves': 79, 'max_depth': 12, 'min_child_samples': 9, 'subsample': 0.771717204705169, 'colsample_bytree': 0.5384524054372584, 'reg_alpha': 0.00044726673537931136, 'reg_lambda': 3.8896373837767744}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,340] Trial 42 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 208, 'learning_rate': 0.03373639616507388, 'num_leaves': 85, 'max_depth': 12, 'min_child_samples': 11, 'subsample': 0.7970252708203625, 'colsample_bytree': 0.6591312376665228, 'reg_alpha': 0.004733321558960654, 'reg_lambda': 1.5374209661326241}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,366] Trial 43 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 144, 'learning_rate': 0.03983935707467048, 'num_leaves': 66, 'max_depth': 11, 'min_child_samples': 10, 'subsample': 0.6967711633304492, 'colsample_bytree': 0.5382061596527341, 'reg_alpha': 0.05234400454322706, 'reg_lambda': 0.2728885556850082}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,398] Trial 44 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 378, 'learning_rate': 0.005138942266773901, 'num_leaves': 92, 'max_depth': 11, 'min_child_samples': 7, 'subsample': 0.6295968062168668, 'colsample_bytree': 0.5002363671177025, 'reg_alpha': 2.6948266407495717e-05, 'reg_lambda': 8.773048375252088}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,426] Trial 45 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 240, 'learning_rate': 0.010470214645831751, 'num_leaves': 71, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.7392598933642482, 'colsample_bytree': 0.8204346631147431, 'reg_alpha': 8.713957062437471, 'reg_lambda': 0.019862291846475394}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,452] Trial 46 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 115, 'learning_rate': 0.05423794826209871, 'num_leaves': 37, 'max_depth': 12, 'min_child_samples': 14, 'subsample': 0.8141937119236371, 'colsample_bytree': 0.5658417731294915, 'reg_alpha': 0.002067797444152558, 'reg_lambda': 0.00021222238807859923}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,493] Trial 47 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 982, 'learning_rate': 0.014474938698668154, 'num_leaves': 52, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7670786549381148, 'colsample_bytree': 0.8685571749182315, 'reg_alpha': 0.015990306595736532, 'reg_lambda': 0.13028357285159034}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,520] Trial 48 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 305, 'learning_rate': 0.059328321321783554, 'num_leaves': 76, 'max_depth': 3, 'min_child_samples': 15, 'subsample': 0.5290291668419294, 'colsample_bytree': 0.6768540307706866, 'reg_alpha': 5.041912977944495e-06, 'reg_lambda': 0.0020500641786521047}. Best is trial 0 with value: 0.04812267077268912.
[I 2026-02-22 20:15:03,546] Trial 49 finished with value: 0.04812267077268912 and parameters: {'n_estimators': 251, 'learning_rate': 0.024095747357435117, 'num_leaves': 96, 'max_depth': 9, 'min_child_samples': 19, 'subsample': 0.8503552098832768, 'colsample_bytree': 0.6098136361991864, 'reg_alpha': 3.7481531495922594e-08, 'reg_lambda': 4.3666536444383826e-05}. Best is trial 0 with value: 0.04812267077268912.

Best MAPE for Severity: 0.0481

Training Final Models...

LGBMRegressor(colsample_bytree=0.7870938530766903,
              learning_rate=0.0842085563039455, max_depth=7,
              min_child_samples=17, n_estimators=130, num_leaves=49,
              reg_alpha=5.244662614053785e-06, reg_lambda=6.834926279053943e-05,
              subsample=0.772587623941132)

In [60]:
# --- 5. RECURSIVE FORECASTING ---
last_date = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

current_history = df.copy()
predictions = []

for period in forecast_range:
    # A. Build Features
    last_3 = current_history.tail(3)
    last_6 = current_history.tail(6) # Need 6 rows for Mean6
    
    # Cyclic Month
    p_month = period.month
    feat_sin = np.sin(2 * np.pi * p_month/12)
    feat_cos = np.cos(2 * np.pi * p_month/12)
    
    input_row = pd.DataFrame([{
        'month_sin': feat_sin,
        'month_cos': feat_cos,
        'Frequency_Lag1': last_3['Frequency'].iloc[-1],
        'Frequency_Lag2': last_3['Frequency'].iloc[-2],
        'Frequency_Lag3': last_3['Frequency'].iloc[-3],
        'Frequency_Mean3': last_3['Frequency'].mean(),
        'Frequency_Mean6': last_6['Frequency'].mean() if len(last_6)>=6 else last_3['Frequency'].mean(),
        'Frequency_Std3': last_3['Frequency'].std(),
        
        'Severity_Lag1': last_3['Severity'].iloc[-1],
        'Severity_Lag2': last_3['Severity'].iloc[-2],
        'Severity_Lag3': last_3['Severity'].iloc[-3],
        'Severity_Mean3': last_3['Severity'].mean(),
        'Severity_Mean6': last_6['Severity'].mean() if len(last_6)>=6 else last_3['Severity'].mean(),
        'Severity_Std3': last_3['Severity'].std(),
    }])
    
    # Ensure column order matches training
    input_row = input_row[features]
    
    # B. Predict
    # Note: We optimized on raw data (not log), so we predict raw directly
    pred_freq = final_model_freq.predict(input_row)[0]
    pred_sev = final_model_sev.predict(input_row)[0]
    
    # Safety Capping (Frequency shouldn't be negative)
    pred_freq = max(0, pred_freq)
    pred_sev = max(0, pred_sev)
    
    pred_total_claim = pred_freq * pred_sev
    
    # C. Store & Update
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_freq,
            'Severity': pred_sev,
            'Total_Claim': pred_total_claim
        })
        
    new_row = pd.DataFrame([{
        'Year': period.year,
        'Month': period.month,
        'Frequency': pred_freq,
        'Severity': pred_sev
        # Features will be recalculated in next loop
    }])
    
    current_history = pd.concat([current_history, new_row], ignore_index=True)

# Export
results_df = pd.DataFrame(predictions)
formatted_data = []
for index, row in results_df.iterrows():
    m_id = row['id_month']
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

pd.DataFrame(formatted_data).to_csv('submission_optuna_lgbm.csv', index=False)
print("Optimized submission saved!")

Optimized submission saved!

LightGBM Using Lag 6 and Lag 12

In [61]:
# --- 1. SETUP & FEATURE ENGINEERING ---
# Ensure strict ordering
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

# Create Cyclical Month Features
df['month_sin'] = np.sin(2 * np.pi * df['Month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['Month']/12)

targets = ['Frequency', 'Severity']

for col in targets:
    # Short-term lags
    df[f'{col}_Lag1'] = df[col].shift(1)
    df[f'{col}_Lag2'] = df[col].shift(2)
    df[f'{col}_Lag3'] = df[col].shift(3)
    
    # Long-term / Seasonal lags (Your suggestion)
    df[f'{col}_Lag6'] = df[col].shift(6)
    df[f'{col}_Lag12'] = df[col].shift(12)
    
    # Rolling trends
    df[f'{col}_RollMean3'] = df[col].rolling(window=3).mean()
    df[f'{col}_RollMean6'] = df[col].rolling(window=6).mean()

# IMPORTANT: We do NOT use dropna() here. 
# LightGBM can handle NaNs in the early rows natively.
train_df = df.copy()

# Define Features and Log-Transform Targets
features = [c for c in train_df.columns if 'Lag' in c or 'Roll' in c or 'month_' in c]

y_freq_log = np.log1p(train_df['Frequency'])
y_sev_log = np.log1p(train_df['Severity'])

X = train_df[features]

# --- 2. TRAIN ROBUST LIGHTGBM ---
# Reverting to the simpler parameters that got you 9.48%, avoiding Optuna overfitting
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'n_estimators': 300,       # Kept reasonable to prevent overfitting
    'learning_rate': 0.05,
    'num_leaves': 31,
    'min_child_samples': 3,    # Lowered slightly to allow learning from smaller data
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'random_state': 42,
    'verbose': -1
}

print("Training Frequency Model with Lag 6 & 12...")
model_freq = lgb.LGBMRegressor(**params)
model_freq.fit(X, y_freq_log)

print("Training Severity Model with Lag 6 & 12...")
model_sev = lgb.LGBMRegressor(**params)
model_sev.fit(X, y_sev_log)

print("Training Complete.")

Training Frequency Model with Lag 6 & 12...
Training Severity Model with Lag 6 & 12...
Training Complete.

In [62]:
# --- 3. RECURSIVE FORECASTING (Aug - Dec 2025) ---
last_date = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

current_history = df.copy()
predictions = []

print(f"\nForecasting from {forecast_range[0]} to {forecast_range[-1]}...")

for period in forecast_range:
    # Cyclic Month
    p_month = period.month
    feat_sin = np.sin(2 * np.pi * p_month/12)
    feat_cos = np.cos(2 * np.pi * p_month/12)
    
    # Safely extract lags (if history is too short for some reason, use NaN)
    def get_lag(col, n):
        if len(current_history) >= n:
            return current_history[col].iloc[-n]
        return np.nan

    def get_roll_mean(col, n):
        if len(current_history) >= n:
            return current_history[col].tail(n).mean()
        return current_history[col].mean()

    # Construct Feature Dictionary matching training features
    input_dict = {
        'month_sin': feat_sin,
        'month_cos': feat_cos,
        
        'Frequency_Lag1': get_lag('Frequency', 1),
        'Frequency_Lag2': get_lag('Frequency', 2),
        'Frequency_Lag3': get_lag('Frequency', 3),
        'Frequency_Lag6': get_lag('Frequency', 6),
        'Frequency_Lag12': get_lag('Frequency', 12),
        'Frequency_RollMean3': get_roll_mean('Frequency', 3),
        'Frequency_RollMean6': get_roll_mean('Frequency', 6),
        
        'Severity_Lag1': get_lag('Severity', 1),
        'Severity_Lag2': get_lag('Severity', 2),
        'Severity_Lag3': get_lag('Severity', 3),
        'Severity_Lag6': get_lag('Severity', 6),
        'Severity_Lag12': get_lag('Severity', 12),
        'Severity_RollMean3': get_roll_mean('Severity', 3),
        'Severity_RollMean6': get_roll_mean('Severity', 6),
    }
    
    # Convert to DataFrame to ensure correct column order
    input_row = pd.DataFrame([input_dict])[features]
    
    # Predict (Inverse Log Transform)
    pred_freq = np.expm1(model_freq.predict(input_row)[0])
    pred_sev = np.expm1(model_sev.predict(input_row)[0])
    
    # Calculate Total Claim
    pred_total_claim = pred_freq * pred_sev
    
    # Store Prediction
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_freq,
            'Severity': pred_sev,
            'Total_Claim': pred_total_claim
        })
        
    # Update History for next step
    new_row = pd.DataFrame([{
        'Year': period.year,
        'Month': period.month,
        'Frequency': pred_freq,
        'Severity': pred_sev
    }])
    current_history = pd.concat([current_history, new_row], ignore_index=True)

results_df = pd.DataFrame(predictions)
print("\nForecast Results:")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])

Forecasting from 2025-08 to 2025-12...

Forecast Results:
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 249.203942 55758378.477251 13895207709.053745
1      2025-09 248.645809 55589285.637824 13822042887.137014
2      2025-10 242.784833 49440718.891631 12003456664.984371
3      2025-11 245.368014 51542662.671333 12646920777.091873
4      2025-12 232.962684 54713340.244874 12746166617.062954

In [63]:
# --- 4. FORMAT FOR SUBMISSION ---
formatted_data = []

for index, row in results_df.iterrows():
    m_id = row['id_month']
    
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

submission_df = pd.DataFrame(formatted_data)
submission_df.to_csv('submission_lgbm_lag12.csv', index=False)

print("\nSuccessfully saved to 'submission_lgbm_lag12.csv'")

Successfully saved to 'submission_lgbm_lag12.csv'

GLM Training

In [64]:
import pandas as pd
import numpy as np
from sklearn.linear_model import PoissonRegressor, GammaRegressor

# --- 1. SETUP & FEATURE ENGINEERING ---
# Ensure strict ordering
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

# Create a Time Index for the overall upward/downward trend (0, 1, 2, 3...)
df['Time_Index'] = np.arange(len(df))

# Create Cyclical Month Features for the recurring wave (Seasonality)
df['month_sin'] = np.sin(2 * np.pi * df['Month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['Month']/12)

# Features: We ONLY use Time and Seasonality. No lags! No lost data!
features = ['Time_Index', 'month_sin', 'month_cos']
X = df[features]

# Targets
y_freq = df['Frequency']

# Gamma requires strictly positive values (>0). 
# If there are months with 0 severity, we add a tiny fraction to prevent errors.
y_sev = df['Severity'].apply(lambda x: x if x > 0 else 1e-6)

# --- 2. TRAIN GLMs ---
# Poisson for Frequency (Counts)
print("Training Poisson GLM for Frequency...")
model_freq = PoissonRegressor(alpha=1e-4, max_iter=1000)
model_freq.fit(X, y_freq)

# Gamma for Severity (Costs)
print("Training Gamma GLM for Severity...")
model_sev = GammaRegressor(alpha=1e-4, max_iter=1000)
model_sev.fit(X, y_sev)

print("Training Complete.")

Training Poisson GLM for Frequency...
Training Gamma GLM for Severity...
Training Complete.

In [65]:
# --- 3. FORECASTING (Aug - Dec 2025) ---
last_date = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

# The next Time_Index continues from where the training data ended
next_time_index = df['Time_Index'].max() + 1
predictions = []

print(f"\nForecasting from {forecast_range[0]} to {forecast_range[-1]}...")

for period in forecast_range:
    p_month = period.month
    
    # Build the future feature row
    input_row = pd.DataFrame([{
        'Time_Index': next_time_index,
        'month_sin': np.sin(2 * np.pi * p_month/12),
        'month_cos': np.cos(2 * np.pi * p_month/12)
    }])
    
    # Predict directly
    pred_freq = model_freq.predict(input_row)[0]
    pred_sev = model_sev.predict(input_row)[0]
    
    # Calculate Total Claim
    pred_total_claim = pred_freq * pred_sev
    
    # Store Prediction
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_freq,
            'Severity': pred_sev,
            'Total_Claim': pred_total_claim
        })
        
    next_time_index += 1 # Advance the clock for the next month

results_df = pd.DataFrame(predictions)
print("\nForecast Results:")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])

Forecasting from 2025-08 to 2025-12...

Forecast Results:
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 234.417536 51915705.703318 12169951792.539413
1      2025-09 236.005133 52136989.569535 12304597154.549131
2      2025-10 236.384220 52690071.936137 12455101531.121786
3      2025-11 235.131964 53396696.292686 12555270079.109734
4      2025-12 232.293137 54031567.432815 12551162278.798311

In [66]:
# --- 4. FORMAT FOR SUBMISSION ---
formatted_data = []

for index, row in results_df.iterrows():
    m_id = row['id_month']
    
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

submission_df = pd.DataFrame(formatted_data)
submission_df.to_csv('submission_glm.csv', index=False)

print("\nSuccessfully saved to 'submission_glm.csv'")

Successfully saved to 'submission_glm.csv'

Light GBM + GLM Training

In [67]:
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.linear_model import PoissonRegressor, GammaRegressor

# --- 1. SETUP & FEATURE ENGINEERING ---
# Ensure strict ordering
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

# A. Features for GLM (Trend & Seasonality)
df['Time_Index'] = np.arange(len(df))
df['month_sin'] = np.sin(2 * np.pi * df['Month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['Month']/12)

# B. Features for LightGBM (Lags & Rolling Means)
targets = ['Frequency', 'Severity']
for col in targets:
    df[f'{col}_Lag1'] = df[col].shift(1)
    df[f'{col}_Lag2'] = df[col].shift(2)
    df[f'{col}_Lag3'] = df[col].shift(3)
    df[f'{col}_RollMean3'] = df[col].rolling(window=3).mean()

# Separate training sets
# LightGBM needs rows with lags (drops first 3)
train_lgbm = df.dropna().copy()
features_lgbm = [c for c in train_lgbm.columns if 'Lag' in c or 'Roll' in c or 'month_' in c]

# GLM uses all rows (no lags needed)
features_glm = ['Time_Index', 'month_sin', 'month_cos']

# --- 2. TRAIN THE MODELS ---

# A. Train LightGBM (Using the settings from your 9.48% run)
y_freq_log = np.log1p(train_lgbm['Frequency'])
y_sev_log = np.log1p(train_lgbm['Severity'])

lgbm_params = {
    'objective': 'regression', 'metric': 'rmse', 'boosting_type': 'gbdt',
    'n_estimators': 500, 'learning_rate': 0.05, 'num_leaves': 31,
    'min_child_samples': 5, 'subsample': 0.8, 'colsample_bytree': 0.8,
    'random_state': 42, 'verbose': -1
}

print("Training LightGBM Models...")
model_freq_lgbm = lgb.LGBMRegressor(**lgbm_params).fit(train_lgbm[features_lgbm], y_freq_log)
model_sev_lgbm = lgb.LGBMRegressor(**lgbm_params).fit(train_lgbm[features_lgbm], y_sev_log)

# B. Train GLM
print("Training GLM Models...")
y_freq_glm = df['Frequency']
y_sev_glm = df['Severity'].apply(lambda x: x if x > 0 else 1e-6)

model_freq_glm = PoissonRegressor(alpha=1e-4, max_iter=1000).fit(df[features_glm], y_freq_glm)
model_sev_glm = GammaRegressor(alpha=1e-4, max_iter=1000).fit(df[features_glm], y_sev_glm)

print("Training Complete. Proceeding to Hybrid Forecast.")

# --- 3. RECURSIVE HYBRID FORECASTING (Aug - Dec 2025) ---
last_date = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

current_history = df.copy()
next_time_index = df['Time_Index'].max() + 1
predictions = []

for period in forecast_range:
    p_month = period.month
    feat_sin = np.sin(2 * np.pi * p_month/12)
    feat_cos = np.cos(2 * np.pi * p_month/12)
    
    # 1. Prepare LightGBM Inputs (from history)
    last_3 = current_history.tail(3)
    input_lgbm = pd.DataFrame([{
        'month_sin': feat_sin, 'month_cos': feat_cos,
        'Frequency_Lag1': last_3['Frequency'].iloc[-1],
        'Frequency_Lag2': last_3['Frequency'].iloc[-2],
        'Frequency_Lag3': last_3['Frequency'].iloc[-3],
        'Frequency_RollMean3': last_3['Frequency'].mean(),
        'Severity_Lag1': last_3['Severity'].iloc[-1],
        'Severity_Lag2': last_3['Severity'].iloc[-2],
        'Severity_Lag3': last_3['Severity'].iloc[-3],
        'Severity_RollMean3': last_3['Severity'].mean(),
    }])[features_lgbm] # Ensure correct column order
    
    # 2. Prepare GLM Inputs
    input_glm = pd.DataFrame([{
        'Time_Index': next_time_index,
        'month_sin': feat_sin, 'month_cos': feat_cos
    }])
    
    # 3. Get Predictions from Both
    pred_freq_lgbm = np.expm1(model_freq_lgbm.predict(input_lgbm)[0])
    pred_sev_lgbm = np.expm1(model_sev_lgbm.predict(input_lgbm)[0])
    
    pred_freq_glm = model_freq_glm.predict(input_glm)[0]
    pred_sev_glm = model_sev_glm.predict(input_glm)[0]
    
    # 4. ENSEMBLE: Average the predictions (50/50 split)
    # You can tweak this weight. Example: 0.6 * LGBM + 0.4 * GLM
    final_pred_freq = (pred_freq_lgbm + pred_freq_glm) / 2
    final_pred_sev = (pred_sev_lgbm + pred_sev_glm) / 2
    final_total_claim = final_pred_freq * final_pred_sev
    
    # Store Prediction
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': final_pred_freq,
            'Severity': final_pred_sev,
            'Total_Claim': final_total_claim
        })
        
    # Update History with the HYBRID prediction so next month's lags are stable
    new_row = pd.DataFrame([{
        'Year': period.year, 'Month': period.month,
        'Frequency': final_pred_freq, 'Severity': final_pred_sev
    }])
    current_history = pd.concat([current_history, new_row], ignore_index=True)
    next_time_index += 1

# --- 4. FORMAT FOR SUBMISSION ---
results_df = pd.DataFrame(predictions)
formatted_data = []

for index, row in results_df.iterrows():
    m_id = row['id_month']
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

submission_df = pd.DataFrame(formatted_data)
submission_df.to_csv('submission_hybrid.csv', index=False)

print("\nForecast Results (Hybrid Model):")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])
print("\nSuccessfully saved to 'submission_hybrid.csv'")

Training LightGBM Models...
Training GLM Models...
Training Complete. Proceeding to Hybrid Forecast.

Forecast Results (Hybrid Model):
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 234.116896 52356576.998319 12257559303.864676
1      2025-09 241.576701 50485235.695374 12196056664.197708
2      2025-10 240.866853 51896230.583004 12500081731.022455
3      2025-11 234.669598 53127141.829978 12467325035.936821
4      2025-12 229.933321 51869963.970526 11926633085.759604

Successfully saved to 'submission_hybrid.csv'

Rich DF LightGBM

In [69]:
import pandas as pd
import numpy as np
import lightgbm as lgb

# --- 1. EXTRACT RICH FEATURES FROM RAW DATA ---
# Ensure dates are datetime objects
claims_df['Tanggal Pasien Masuk RS'] = pd.to_datetime(claims_df['Tanggal Pasien Masuk RS'])
claims_df['Tanggal Pasien Keluar RS'] = pd.to_datetime(claims_df['Tanggal Pasien Keluar RS'])

# A. Calculate Length of Stay (LOS) in days. 
# If they leave the same day, we count it as 1 day to avoid zeros skewing averages.
claims_df['LOS'] = (claims_df['Tanggal Pasien Keluar RS'] - claims_df['Tanggal Pasien Masuk RS']).dt.days
claims_df['LOS'] = claims_df['LOS'].replace(0, 1)

# B. Convert Cashless indicator to binary
claims_df['Is_Cashless'] = (claims_df['Reimburse/Cashless'] == 'C').astype(int)

# C. Calculate Approval Ratio (How much of the bill we actually paid)
# Add a tiny number to denominator to prevent division by zero
claims_df['Approval_Ratio'] = claims_df['Nominal Klaim Yang Disetujui'] / (claims_df['Nominal Biaya RS Yang Terjadi'] + 1e-6)

# --- 2. AGGREGATE INTO A NEW 'RICH' MONTHLY DATAFRAME ---
monthly_data = []
grouped = claims_df.groupby(['Year', 'Month', 'Period'])

for (year, month, period), group in grouped:
    monthly_data.append({
        'Period': period,
        'Year': year,
        'Month': month,
        
        # Original Targets
        'Frequency': len(group),
        'Severity': group['Nominal Klaim Yang Disetujui'].mean(),
        'Total_Claim': group['Nominal Klaim Yang Disetujui'].sum(),
        
        # NEW: Portfolio Characteristics
        'Mean_LOS': group['LOS'].mean(),
        'Cashless_Ratio': group['Is_Cashless'].mean(),
        'Inpatient_Ratio': group['Is_IP'].mean(),
        'Mean_Approval_Ratio': group['Approval_Ratio'].mean(),
        'Unique_Claimants': group['Nomor Polis'].nunique()
    })

rich_df = pd.DataFrame(monthly_data).sort_values(by=['Year', 'Month']).reset_index(drop=True)

# --- 3. TIME-SERIES FEATURE ENGINEERING ---
rich_df['month_sin'] = np.sin(2 * np.pi * rich_df['Month']/12)
rich_df['month_cos'] = np.cos(2 * np.pi * rich_df['Month']/12)

# Create Lags and Rolling Means for Targets
for col in ['Frequency', 'Severity']:
    rich_df[f'{col}_Lag1'] = rich_df[col].shift(1)
    rich_df[f'{col}_Lag2'] = rich_df[col].shift(2)
    rich_df[f'{col}_Lag3'] = rich_df[col].shift(3)
    rich_df[f'{col}_RollMean3'] = rich_df[col].rolling(window=3).mean()

# Create Lags for the new Portfolio Characteristics
for col in ['Mean_LOS', 'Cashless_Ratio', 'Inpatient_Ratio', 'Mean_Approval_Ratio']:
    rich_df[f'{col}_Lag1'] = rich_df[col].shift(1)
    rich_df[f'{col}_RollMean3'] = rich_df[col].rolling(window=3).mean()

# Drop NaNs for training
train_df = rich_df.dropna().copy()

In [71]:
train_df.head()

,Period,Year,Month,Frequency,Severity,Total_Claim,Mean_LOS,Cashless_Ratio,Inpatient_Ratio,Mean_Approval_Ratio,...,Severity_Lag3,Severity_RollMean3,Mean_LOS_Lag1,Mean_LOS_RollMean3,Cashless_Ratio_Lag1,Cashless_Ratio_RollMean3,Inpatient_Ratio_Lag1,Inpatient_Ratio_RollMean3,Mean_Approval_Ratio_Lag1,Mean_Approval_Ratio_RollMean3
3,2024-04,2024,4,239,47870555.558787,11441062778.549999,1.870293,0.364017,0.669456,0.883684,...,67089342.682759,55327604.026867,2.118705,2.071653,0.377698,0.365828,0.705036,0.682523,0.891701,0.894892
4,2024-05,2024,5,263,46431413.766426,12211461820.570000,1.840304,0.376426,0.619772,0.994090,...,66632910.865882,48593771.660382,1.870293,1.943101,0.364017,0.372713,0.669456,0.664755,0.883684,0.923158
5,2024-06,2024,6,225,53889631.911244,12125167180.029999,2.035556,0.426667,0.471111,0.891448,...,51479345.655933,49397200.412152,1.840304,1.915384,0.376426,0.389036,0.619772,0.586780,0.994090,0.923074
6,2024-07,2024,7,257,58251037.858949,14970516729.750000,1.661479,0.439689,0.435798,125657076460.025284,...,47870555.558787,52857361.178873,2.035556,1.845779,0.426667,0.414260,0.471111,0.508894,0.891448,41885692153.970276
7,2024-08,2024,8,228,59267262.543465,13512935859.910000,2.210526,0.451754,0.416667,0.889106,...,46431413.766426,57135977.437886,1.661479,1.969187,0.439689,0.439370,0.435798,0.441192,125657076460.025284,41885692153.935280

In [72]:
# --- 4. TRAIN LIGHTGBM ---
features = [c for c in train_df.columns if 'Lag' in c or 'Roll' in c or 'month_' in c]

# Log transform targets
y_freq_log = np.log1p(train_df['Frequency'])
y_sev_log = np.log1p(train_df['Severity'])

X = train_df[features]

params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'n_estimators': 400,
    'learning_rate': 0.03, # Slightly slower learning rate for richer features
    'num_leaves': 25,
    'min_child_samples': 4,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'random_state': 42,
    'verbose': -1
}

print("Training Rich LightGBM for Frequency...")
model_freq = lgb.LGBMRegressor(**params).fit(X, y_freq_log)

print("Training Rich LightGBM for Severity...")
model_sev = lgb.LGBMRegressor(**params).fit(X, y_sev_log)

Training Rich LightGBM for Frequency...
Training Rich LightGBM for Severity...

In [73]:
# --- 5. RECURSIVE FORECASTING ---
last_date = pd.Period(f"{rich_df['Year'].iloc[-1]}-{rich_df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

current_history = rich_df.copy()
predictions = []

# Calculate the stable portfolio assumptions (Last known 3-month average)
stable_assumptions = {
    'Mean_LOS': current_history['Mean_LOS'].tail(3).mean(),
    'Cashless_Ratio': current_history['Cashless_Ratio'].tail(3).mean(),
    'Inpatient_Ratio': current_history['Inpatient_Ratio'].tail(3).mean(),
    'Mean_Approval_Ratio': current_history['Mean_Approval_Ratio'].tail(3).mean()
}

for period in forecast_range:
    p_month = period.month
    last_3 = current_history.tail(3)
    
    # Build Input Row
    input_dict = {
        'month_sin': np.sin(2 * np.pi * p_month/12),
        'month_cos': np.cos(2 * np.pi * p_month/12),
        
        # Target Features
        'Frequency_Lag1': last_3['Frequency'].iloc[-1],
        'Frequency_Lag2': last_3['Frequency'].iloc[-2],
        'Frequency_Lag3': last_3['Frequency'].iloc[-3],
        'Frequency_RollMean3': last_3['Frequency'].mean(),
        
        'Severity_Lag1': last_3['Severity'].iloc[-1],
        'Severity_Lag2': last_3['Severity'].iloc[-2],
        'Severity_Lag3': last_3['Severity'].iloc[-3],
        'Severity_RollMean3': last_3['Severity'].mean(),
        
        # Portfolio Features (Using historical data or stable assumptions if projecting)
        'Mean_LOS_Lag1': last_3['Mean_LOS'].iloc[-1] if not pd.isna(last_3['Mean_LOS'].iloc[-1]) else stable_assumptions['Mean_LOS'],
        'Mean_LOS_RollMean3': last_3['Mean_LOS'].mean() if len(last_3.dropna(subset=['Mean_LOS'])) > 0 else stable_assumptions['Mean_LOS'],
        
        'Cashless_Ratio_Lag1': last_3['Cashless_Ratio'].iloc[-1] if not pd.isna(last_3['Cashless_Ratio'].iloc[-1]) else stable_assumptions['Cashless_Ratio'],
        'Cashless_Ratio_RollMean3': last_3['Cashless_Ratio'].mean() if len(last_3.dropna(subset=['Cashless_Ratio'])) > 0 else stable_assumptions['Cashless_Ratio'],
        
        'Inpatient_Ratio_Lag1': last_3['Inpatient_Ratio'].iloc[-1] if not pd.isna(last_3['Inpatient_Ratio'].iloc[-1]) else stable_assumptions['Inpatient_Ratio'],
        'Inpatient_Ratio_RollMean3': last_3['Inpatient_Ratio'].mean() if len(last_3.dropna(subset=['Inpatient_Ratio'])) > 0 else stable_assumptions['Inpatient_Ratio'],
        
        'Mean_Approval_Ratio_Lag1': last_3['Mean_Approval_Ratio'].iloc[-1] if not pd.isna(last_3['Mean_Approval_Ratio'].iloc[-1]) else stable_assumptions['Mean_Approval_Ratio'],
        'Mean_Approval_Ratio_RollMean3': last_3['Mean_Approval_Ratio'].mean() if len(last_3.dropna(subset=['Mean_Approval_Ratio'])) > 0 else stable_assumptions['Mean_Approval_Ratio'],
    }
    
    # Ensure correct column order
    input_row = pd.DataFrame([input_dict])[features]
    
    # Predict
    pred_freq = np.expm1(model_freq.predict(input_row)[0])
    pred_sev = np.expm1(model_sev.predict(input_row)[0])
    
    pred_total_claim = pred_freq * pred_sev
    
    # Store Prediction
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_freq,
            'Severity': pred_sev,
            'Total_Claim': pred_total_claim
        })
        
    # Update History for next step
    new_row = pd.DataFrame([{
        'Year': period.year,
        'Month': period.month,
        'Frequency': pred_freq,
        'Severity': pred_sev,
        # Carry forward the assumptions so next month's lags work
        'Mean_LOS': stable_assumptions['Mean_LOS'],
        'Cashless_Ratio': stable_assumptions['Cashless_Ratio'],
        'Inpatient_Ratio': stable_assumptions['Inpatient_Ratio'],
        'Mean_Approval_Ratio': stable_assumptions['Mean_Approval_Ratio']
    }])
    current_history = pd.concat([current_history, new_row], ignore_index=True)

In [74]:
# --- 6. FORMAT FOR SUBMISSION ---
results_df = pd.DataFrame(predictions)
formatted_data = []

for index, row in results_df.iterrows():
    m_id = row['id_month']
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

submission_df = pd.DataFrame(formatted_data)
submission_df.to_csv('submission_rich_lgbm.csv', index=False)

print("\nForecast Results:")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])
print("\nSuccessfully saved to 'submission_rich_lgbm.csv'")

Forecast Results:
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 259.831892 54033484.146666 14039622392.962523
1      2025-09 258.907639 50929851.847287 13186127696.116346
2      2025-10 249.913130 51772406.872459 12938604244.242289
3      2025-11 247.993582 51576530.740116 12790648625.005024
4      2025-12 234.486649 48739207.708177 11428693486.747559

Successfully saved to 'submission_rich_lgbm.csv'

Direct Ridge

In [75]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge

# --- 1. SETUP & ISOLATED FEATURE ENGINEERING ---
df = final_df.sort_values(by=['Year', 'Month']).reset_index(drop=True)

# Seasonality
df['month_sin'] = np.sin(2 * np.pi * df['Month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['Month']/12)

# We are now tracking Total Klaim directly as well
targets = ['Frequency', 'Severity', 'Total Klaim']

for col in targets:
    df[f'{col}_Lag1'] = df[col].shift(1)
    df[f'{col}_Lag2'] = df[col].shift(2)
    df[f'{col}_Lag3'] = df[col].shift(3)
    df[f'{col}_RollMean3'] = df[col].rolling(window=3).mean()

train_df = df.dropna().copy()

# --- 2. TRAIN INDEPENDENT RIDGE MODELS ---
# Ridge is highly regularized, preventing the wild swings of Tree models
alpha_val = 1.0 

# Model 1: Frequency (Only sees time and its own history)
features_freq = ['month_sin', 'month_cos', 'Frequency_Lag1', 'Frequency_Lag2', 'Frequency_Lag3', 'Frequency_RollMean3']
model_freq = Ridge(alpha=alpha_val)
model_freq.fit(train_df[features_freq], np.log1p(train_df['Frequency']))

# Model 2: Severity (Only sees time and its own history)
features_sev = ['month_sin', 'month_cos', 'Severity_Lag1', 'Severity_Lag2', 'Severity_Lag3', 'Severity_RollMean3']
model_sev = Ridge(alpha=alpha_val)
model_sev.fit(train_df[features_sev], np.log1p(train_df['Severity']))

# Model 3: Total Claim (DIRECT PREDICTION)
features_total = ['month_sin', 'month_cos', 'Total Klaim_Lag1', 'Total Klaim_Lag2', 'Total Klaim_Lag3', 'Total Klaim_RollMean3']
model_total = Ridge(alpha=alpha_val)
model_total.fit(train_df[features_total], np.log1p(train_df['Total Klaim']))

print("Independent Ridge Models Trained.")

# --- 3. RECURSIVE FORECASTING ---
last_date = pd.Period(f"{df['Year'].iloc[-1]}-{df['Month'].iloc[-1]}", freq='M')
target_start = pd.Period('2025-08', freq='M')
target_end = pd.Period('2025-12', freq='M')
forecast_range = pd.period_range(start=last_date + 1, end=target_end, freq='M')

current_history = df.copy()
predictions = []

for period in forecast_range:
    p_month = period.month
    feat_sin = np.sin(2 * np.pi * p_month/12)
    feat_cos = np.cos(2 * np.pi * p_month/12)
    last_3 = current_history.tail(3)
    
    # Predict Frequency
    row_freq = pd.DataFrame([{'month_sin': feat_sin, 'month_cos': feat_cos,
                              'Frequency_Lag1': last_3['Frequency'].iloc[-1], 'Frequency_Lag2': last_3['Frequency'].iloc[-2],
                              'Frequency_Lag3': last_3['Frequency'].iloc[-3], 'Frequency_RollMean3': last_3['Frequency'].mean()}])[features_freq]
    pred_freq = np.expm1(model_freq.predict(row_freq)[0])
    
    # Predict Severity
    row_sev = pd.DataFrame([{'month_sin': feat_sin, 'month_cos': feat_cos,
                             'Severity_Lag1': last_3['Severity'].iloc[-1], 'Severity_Lag2': last_3['Severity'].iloc[-2],
                             'Severity_Lag3': last_3['Severity'].iloc[-3], 'Severity_RollMean3': last_3['Severity'].mean()}])[features_sev]
    pred_sev = np.expm1(model_sev.predict(row_sev)[0])
    
    # Predict Total Claim DIRECTLY
    row_total = pd.DataFrame([{'month_sin': feat_sin, 'month_cos': feat_cos,
                               'Total Klaim_Lag1': last_3['Total Klaim'].iloc[-1], 'Total Klaim_Lag2': last_3['Total Klaim'].iloc[-2],
                               'Total Klaim_Lag3': last_3['Total Klaim'].iloc[-3], 'Total Klaim_RollMean3': last_3['Total Klaim'].mean()}])[features_total]
    pred_total = np.expm1(model_total.predict(row_total)[0])
    
    # Store
    if period >= target_start:
        predictions.append({
            'Month_Period': str(period),
            'id_month': str(period).replace('-', '_'),
            'Frequency': pred_freq,
            'Severity': pred_sev,
            'Total_Claim': pred_total # Using the direct prediction!
        })
        
    # Update History
    new_row = pd.DataFrame([{
        'Year': period.year, 'Month': period.month,
        'Frequency': pred_freq, 'Severity': pred_sev, 'Total Klaim': pred_total
    }])
    current_history = pd.concat([current_history, new_row], ignore_index=True)

# --- 4. FORMAT AND EXPORT ---
results_df = pd.DataFrame(predictions)
formatted_data = []

for index, row in results_df.iterrows():
    m_id = row['id_month']
    formatted_data.append({'id': f"{m_id}_Claim_Frequency", 'value': row['Frequency']})
    formatted_data.append({'id': f"{m_id}_Claim_Severity", 'value': row['Severity']})
    formatted_data.append({'id': f"{m_id}_Total_Claim", 'value': row['Total_Claim']})

submission_df = pd.DataFrame(formatted_data)
submission_df.to_csv('submission_ridge_direct.csv', index=False)

print("\nForecast Results:")
print(results_df[['Month_Period', 'Frequency', 'Severity', 'Total_Claim']])
print("\nSaved to 'submission_ridge_direct.csv'")

Independent Ridge Models Trained.

Forecast Results:
  Month_Period  Frequency        Severity        Total_Claim
0      2025-08 238.082479 51179458.198422 12305576353.974308
1      2025-09 232.661628 56822963.469276 13337328304.152416
2      2025-10 263.894477 51706971.310517 13666087566.551418
3      2025-11 236.897665 50752414.656465 12214300466.838234
4      2025-12 231.424349 55955939.290475 13076111098.759466

Saved to 'submission_ridge_direct.csv'

c:\Users\Robben's Laptop\.conda\envs\data_science\Lib\site-packages\sklearn\linear_model\_ridge.py:213: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.264436495765169e-20.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T